//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.fps_admi_002_001_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageRoot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageRoot">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrpHdr" type="{urn:hkicl:fps:xsd:fps.admi.002.001.01}GroupHeader"/>
 *         &lt;element name="OrgnlGrpHdr" type="{urn:hkicl:fps:xsd:fps.admi.002.001.01}OriginalGroupHeader"/>
 *         &lt;element name="RcptMdRslt" type="{urn:hkicl:fps:xsd:fps.admi.002.001.01}Result"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageRoot", propOrder = {
    "grpHdr",
    "orgnlGrpHdr",
    "rcptMdRslt"
})
public class MessageRoot {

    @XmlElement(name = "GrpHdr", required = true)
    protected GroupHeader grpHdr;
    @XmlElement(name = "OrgnlGrpHdr", required = true)
    protected OriginalGroupHeader orgnlGrpHdr;
    @XmlElement(name = "RcptMdRslt", required = true)
    protected Result rcptMdRslt;

    /**
     * Gets the value of the grpHdr property.
     * 
     * @return
     *     possible object is
     *     {@link GroupHeader }
     *     
     */
    public GroupHeader getGrpHdr() {
        return grpHdr;
    }

    /**
     * Sets the value of the grpHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupHeader }
     *     
     */
    public void setGrpHdr(GroupHeader value) {
        this.grpHdr = value;
    }

    /**
     * Gets the value of the orgnlGrpHdr property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalGroupHeader }
     *     
     */
    public OriginalGroupHeader getOrgnlGrpHdr() {
        return orgnlGrpHdr;
    }

    /**
     * Sets the value of the orgnlGrpHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalGroupHeader }
     *     
     */
    public void setOrgnlGrpHdr(OriginalGroupHeader value) {
        this.orgnlGrpHdr = value;
    }

    /**
     * Gets the value of the rcptMdRslt property.
     * 
     * @return
     *     possible object is
     *     {@link Result }
     *     
     */
    public Result getRcptMdRslt() {
        return rcptMdRslt;
    }

    /**
     * Sets the value of the rcptMdRslt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Result }
     *     
     */
    public void setRcptMdRslt(Result value) {
        this.rcptMdRslt = value;
    }

}
