//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.16 at 11:35:46 上午 CST 
//


package com.forms.ffp.adaptor.jaxb.participant.request.ffpcto01;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.forms.ffp.adaptor.jaxb.participant.request.BODY;


/**
 * <p>Java class for FFPCTO01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FFPCTO01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SrcRefNm" type="{}RestrictedNZText_Max30"/>
 *         &lt;element name="SrvcMode" type="{}UpperCaseNumericText_Exact2"/>
 *         &lt;element name="PymtCatPrps" type="{}UpperCaseNumericText_Exact6"/>
 *         &lt;element name="AcctVerf" type="{}UpperCaseNumericText_Exact15"/>
 *         &lt;element name="SettlDate" type="{}DateTypeNoSplit"/>
 *         &lt;element name="SettlAmt" type="{}Restricted15Digit2AmountType"/>
 *         &lt;element name="SettlCcy" type="{}UpperCaseNumericText_Exact3"/>
 *         &lt;element name="InstrAmt" type="{}Restricted15Digit2AmountType" minOccurs="0"/>
 *         &lt;element name="InstrCcy" type="{}UpperCaseNumericText_Exact3" minOccurs="0"/>
 *         &lt;element name="ChrgrsAgent" type="{}FPSPARTICIPANTID" minOccurs="0"/>
 *         &lt;element name="ChrgrsAmt" type="{}Restricted15Digit2AmountType" minOccurs="0"/>
 *         &lt;element name="ChrgrsCcy" type="{}UpperCaseNumericText_Exact3" minOccurs="0"/>
 *         &lt;element name="DbtrNm" type="{}RestrictedFINZText_Max34"/>
 *         &lt;element name="DbtrAcTp" type="{}UpperCaseNumericText_Exact4"/>
 *         &lt;element name="DbtrAcNo" type="{}RestrictedFINZText_Max34"/>
 *         &lt;element name="DbtrOrgIdAnyBIC" type="{}UpperCaseNumericText_Exact11" minOccurs="0"/>
 *         &lt;element name="DbtrOrgIdOthrId" type="{}RestrictedFINZText_Max35" minOccurs="0"/>
 *         &lt;element name="DbtrOrgIdOthrIdSchmeNm" type="{}UpperCaseNumericText_Exact4" minOccurs="0"/>
 *         &lt;element name="DbtrOrgIdOthrIssr" type="{}RestrictedFINZText_Max35" minOccurs="0"/>
 *         &lt;element name="DbtrPrvtIdOthrId" type="{}RestrictedFINZText_Max35" minOccurs="0"/>
 *         &lt;element name="DbtrPrvtIdOthrIdSchmeNm" type="{}UpperCaseNumericText_Exact4" minOccurs="0"/>
 *         &lt;element name="DbtrPrvtIdOthrIssr" type="{}RestrictedFINZText_Max35" minOccurs="0"/>
 *         &lt;element name="DbtrContPhone" type="{}PhoneNumber" minOccurs="0"/>
 *         &lt;element name="DbtrContEmailAddr" type="{}RestrictedFINZText_Max254" minOccurs="0"/>
 *         &lt;element name="CdtrAgent" type="{}FPSPARTICIPANTID"/>
 *         &lt;element name="CdtrNm" type="{}RestrictedUnicodeTextMax140"/>
 *         &lt;element name="CdtrAcTp" type="{}UpperCaseNumericText_Exact3"/>
 *         &lt;element name="CdtrAcNo" type="{}RestrictedFINZText_Max34"/>
 *         &lt;element name="CdtrOrgIdAnyBIC" type="{}UpperCaseNumericText_Exact11" minOccurs="0"/>
 *         &lt;element name="CdtrOrgIdOthrId" type="{}RestrictedFINZText_Max35" minOccurs="0"/>
 *         &lt;element name="CdtrOrgIdOthrIdSchmeNm" type="{}UpperCaseNumericText_Exact4" minOccurs="0"/>
 *         &lt;element name="CdtrOrgIdOthrIssr" type="{}RestrictedFINZText_Max35" minOccurs="0"/>
 *         &lt;element name="CdtrPrvtIdOthrId" type="{}RestrictedFINZText_Max35" minOccurs="0"/>
 *         &lt;element name="CdtrPrvtIdOthrIdSchmeNm" type="{}UpperCaseNumericText_Exact4" minOccurs="0"/>
 *         &lt;element name="CdtrPrvtIdOthrIssr" type="{}RestrictedFINZText_Max35" minOccurs="0"/>
 *         &lt;element name="CdtrContPhone" type="{}PhoneNumber" minOccurs="0"/>
 *         &lt;element name="CdtrContEmailAddr" type="{}RestrictedFINZText_Max254" minOccurs="0"/>
 *         &lt;element name="pytPurpType" type="{}UpperCaseNumericText_Exact5"/>
 *         &lt;element name="pytPurp" type="{}RestrictedUnicodeTextMax140"/>
 *         &lt;element name="RemInfo" type="{}RestrictedUnicodeTextMax140"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FFPCTO01", propOrder = {
    "srcRefNm",
    "srvcMode",
    "pymtCatPrps",
    "acctVerf",
    "settlDate",
    "settlAmt",
    "settlCcy",
    "instrAmt",
    "instrCcy",
    "chrgrsAgent",
    "chrgrsAmt",
    "chrgrsCcy",
    "dbtrNm",
    "dbtrAcTp",
    "dbtrAcNo",
    "dbtrOrgIdAnyBIC",
    "dbtrOrgIdOthrId",
    "dbtrOrgIdOthrIdSchmeNm",
    "dbtrOrgIdOthrIssr",
    "dbtrPrvtIdOthrId",
    "dbtrPrvtIdOthrIdSchmeNm",
    "dbtrPrvtIdOthrIssr",
    "dbtrContPhone",
    "dbtrContEmailAddr",
    "cdtrAgent",
    "cdtrNm",
    "cdtrAcTp",
    "cdtrAcNo",
    "cdtrOrgIdAnyBIC",
    "cdtrOrgIdOthrId",
    "cdtrOrgIdOthrIdSchmeNm",
    "cdtrOrgIdOthrIssr",
    "cdtrPrvtIdOthrId",
    "cdtrPrvtIdOthrIdSchmeNm",
    "cdtrPrvtIdOthrIssr",
    "cdtrContPhone",
    "cdtrContEmailAddr",
    "pytPurpType",
    "pytPurp",
    "remInfo"
})
public class FFPCTO01 extends BODY{

    @XmlElement(name = "SrcRefNm", required = true)
    protected String srcRefNm;
    @XmlElement(name = "SrvcMode", required = true)
    protected String srvcMode;
    @XmlElement(name = "PymtCatPrps", required = true)
    protected String pymtCatPrps;
    @XmlElement(name = "AcctVerf", required = true)
    protected String acctVerf;
    @XmlElement(name = "SettlDate", required = true)
    protected String settlDate;
    @XmlElement(name = "SettlAmt", required = true)
    protected BigDecimal settlAmt;
    @XmlElement(name = "SettlCcy", required = true)
    protected String settlCcy;
    @XmlElement(name = "InstrAmt")
    protected BigDecimal instrAmt;
    @XmlElement(name = "InstrCcy")
    protected String instrCcy;
    @XmlElement(name = "ChrgrsAgent")
    protected FPSPARTICIPANTID chrgrsAgent;
    @XmlElement(name = "ChrgrsAmt")
    protected BigDecimal chrgrsAmt;
    @XmlElement(name = "ChrgrsCcy")
    protected String chrgrsCcy;
    @XmlElement(name = "DbtrNm", required = true)
    protected String dbtrNm;
    @XmlElement(name = "DbtrAcTp", required = true)
    protected String dbtrAcTp;
    @XmlElement(name = "DbtrAcNo", required = true)
    protected String dbtrAcNo;
    @XmlElement(name = "DbtrOrgIdAnyBIC")
    protected String dbtrOrgIdAnyBIC;
    @XmlElement(name = "DbtrOrgIdOthrId")
    protected String dbtrOrgIdOthrId;
    @XmlElement(name = "DbtrOrgIdOthrIdSchmeNm")
    protected String dbtrOrgIdOthrIdSchmeNm;
    @XmlElement(name = "DbtrOrgIdOthrIssr")
    protected String dbtrOrgIdOthrIssr;
    @XmlElement(name = "DbtrPrvtIdOthrId")
    protected String dbtrPrvtIdOthrId;
    @XmlElement(name = "DbtrPrvtIdOthrIdSchmeNm")
    protected String dbtrPrvtIdOthrIdSchmeNm;
    @XmlElement(name = "DbtrPrvtIdOthrIssr")
    protected String dbtrPrvtIdOthrIssr;
    @XmlElement(name = "DbtrContPhone")
    protected String dbtrContPhone;
    @XmlElement(name = "DbtrContEmailAddr")
    protected String dbtrContEmailAddr;
    @XmlElement(name = "CdtrAgent", required = true)
    protected FPSPARTICIPANTID cdtrAgent;
    @XmlElement(name = "CdtrNm", required = true)
    protected String cdtrNm;
    @XmlElement(name = "CdtrAcTp", required = true)
    protected String cdtrAcTp;
    @XmlElement(name = "CdtrAcNo", required = true)
    protected String cdtrAcNo;
    @XmlElement(name = "CdtrOrgIdAnyBIC")
    protected String cdtrOrgIdAnyBIC;
    @XmlElement(name = "CdtrOrgIdOthrId")
    protected String cdtrOrgIdOthrId;
    @XmlElement(name = "CdtrOrgIdOthrIdSchmeNm")
    protected String cdtrOrgIdOthrIdSchmeNm;
    @XmlElement(name = "CdtrOrgIdOthrIssr")
    protected String cdtrOrgIdOthrIssr;
    @XmlElement(name = "CdtrPrvtIdOthrId")
    protected String cdtrPrvtIdOthrId;
    @XmlElement(name = "CdtrPrvtIdOthrIdSchmeNm")
    protected String cdtrPrvtIdOthrIdSchmeNm;
    @XmlElement(name = "CdtrPrvtIdOthrIssr")
    protected String cdtrPrvtIdOthrIssr;
    @XmlElement(name = "CdtrContPhone")
    protected String cdtrContPhone;
    @XmlElement(name = "CdtrContEmailAddr")
    protected String cdtrContEmailAddr;
    @XmlElement
    protected String pytPurpType;
    @XmlElement
    protected String pytPurp;
    @XmlElement(name = "RemInfo")
    protected String remInfo;

    /**
     * Gets the value of the srcRefNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcRefNm() {
        return srcRefNm;
    }

    /**
     * Sets the value of the srcRefNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcRefNm(String value) {
        this.srcRefNm = value;
    }

    /**
     * Gets the value of the srvcMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrvcMode() {
        return srvcMode;
    }

    /**
     * Sets the value of the srvcMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrvcMode(String value) {
        this.srvcMode = value;
    }

    /**
     * Gets the value of the pymtCatPrps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPymtCatPrps() {
        return pymtCatPrps;
    }

    /**
     * Sets the value of the pymtCatPrps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPymtCatPrps(String value) {
        this.pymtCatPrps = value;
    }

    /**
     * Gets the value of the acctVerf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctVerf() {
        return acctVerf;
    }

    /**
     * Sets the value of the acctVerf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctVerf(String value) {
        this.acctVerf = value;
    }

    /**
     * Gets the value of the settlDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlDate() {
        return settlDate;
    }

    /**
     * Sets the value of the settlDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlDate(String value) {
        this.settlDate = value;
    }

    /**
     * Gets the value of the settlAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSettlAmt() {
        return settlAmt;
    }

    /**
     * Sets the value of the settlAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSettlAmt(BigDecimal value) {
        this.settlAmt = value;
    }

    /**
     * Gets the value of the settlCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlCcy() {
        return settlCcy;
    }

    /**
     * Sets the value of the settlCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlCcy(String value) {
        this.settlCcy = value;
    }

    /**
     * Gets the value of the instrAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInstrAmt() {
        return instrAmt;
    }

    /**
     * Sets the value of the instrAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInstrAmt(BigDecimal value) {
        this.instrAmt = value;
    }

    /**
     * Gets the value of the instrCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrCcy() {
        return instrCcy;
    }

    /**
     * Sets the value of the instrCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrCcy(String value) {
        this.instrCcy = value;
    }

    /**
     * Gets the value of the chrgrsAgent property.
     * 
     * @return
     *     possible object is
     *     {@link FPSPARTICIPANTID }
     *     
     */
    public FPSPARTICIPANTID getChrgrsAgent() {
        return chrgrsAgent;
    }

    /**
     * Sets the value of the chrgrsAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPSPARTICIPANTID }
     *     
     */
    public void setChrgrsAgent(FPSPARTICIPANTID value) {
        this.chrgrsAgent = value;
    }

    /**
     * Gets the value of the chrgrsAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChrgrsAmt() {
        return chrgrsAmt;
    }

    /**
     * Sets the value of the chrgrsAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChrgrsAmt(BigDecimal value) {
        this.chrgrsAmt = value;
    }

    /**
     * Gets the value of the chrgrsCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChrgrsCcy() {
        return chrgrsCcy;
    }

    /**
     * Sets the value of the chrgrsCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChrgrsCcy(String value) {
        this.chrgrsCcy = value;
    }

    /**
     * Gets the value of the dbtrNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrNm() {
        return dbtrNm;
    }

    /**
     * Sets the value of the dbtrNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrNm(String value) {
        this.dbtrNm = value;
    }

    /**
     * Gets the value of the dbtrAcTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrAcTp() {
        return dbtrAcTp;
    }

    /**
     * Sets the value of the dbtrAcTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrAcTp(String value) {
        this.dbtrAcTp = value;
    }

    /**
     * Gets the value of the dbtrAcNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrAcNo() {
        return dbtrAcNo;
    }

    /**
     * Sets the value of the dbtrAcNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrAcNo(String value) {
        this.dbtrAcNo = value;
    }

    /**
     * Gets the value of the dbtrOrgIdAnyBIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrOrgIdAnyBIC() {
        return dbtrOrgIdAnyBIC;
    }

    /**
     * Sets the value of the dbtrOrgIdAnyBIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrOrgIdAnyBIC(String value) {
        this.dbtrOrgIdAnyBIC = value;
    }

    /**
     * Gets the value of the dbtrOrgIdOthrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrOrgIdOthrId() {
        return dbtrOrgIdOthrId;
    }

    /**
     * Sets the value of the dbtrOrgIdOthrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrOrgIdOthrId(String value) {
        this.dbtrOrgIdOthrId = value;
    }

    /**
     * Gets the value of the dbtrOrgIdOthrIdSchmeNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrOrgIdOthrIdSchmeNm() {
        return dbtrOrgIdOthrIdSchmeNm;
    }

    /**
     * Sets the value of the dbtrOrgIdOthrIdSchmeNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrOrgIdOthrIdSchmeNm(String value) {
        this.dbtrOrgIdOthrIdSchmeNm = value;
    }

    /**
     * Gets the value of the dbtrOrgIdOthrIssr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrOrgIdOthrIssr() {
        return dbtrOrgIdOthrIssr;
    }

    /**
     * Sets the value of the dbtrOrgIdOthrIssr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrOrgIdOthrIssr(String value) {
        this.dbtrOrgIdOthrIssr = value;
    }

    /**
     * Gets the value of the dbtrPrvtIdOthrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrPrvtIdOthrId() {
        return dbtrPrvtIdOthrId;
    }

    /**
     * Sets the value of the dbtrPrvtIdOthrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrPrvtIdOthrId(String value) {
        this.dbtrPrvtIdOthrId = value;
    }

    /**
     * Gets the value of the dbtrPrvtIdOthrIdSchmeNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrPrvtIdOthrIdSchmeNm() {
        return dbtrPrvtIdOthrIdSchmeNm;
    }

    /**
     * Sets the value of the dbtrPrvtIdOthrIdSchmeNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrPrvtIdOthrIdSchmeNm(String value) {
        this.dbtrPrvtIdOthrIdSchmeNm = value;
    }

    /**
     * Gets the value of the dbtrPrvtIdOthrIssr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrPrvtIdOthrIssr() {
        return dbtrPrvtIdOthrIssr;
    }

    /**
     * Sets the value of the dbtrPrvtIdOthrIssr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrPrvtIdOthrIssr(String value) {
        this.dbtrPrvtIdOthrIssr = value;
    }

    /**
     * Gets the value of the dbtrContPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrContPhone() {
        return dbtrContPhone;
    }

    /**
     * Sets the value of the dbtrContPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrContPhone(String value) {
        this.dbtrContPhone = value;
    }

    /**
     * Gets the value of the dbtrContEmailAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrContEmailAddr() {
        return dbtrContEmailAddr;
    }

    /**
     * Sets the value of the dbtrContEmailAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrContEmailAddr(String value) {
        this.dbtrContEmailAddr = value;
    }

    /**
     * Gets the value of the cdtrAgent property.
     * 
     * @return
     *     possible object is
     *     {@link FPSPARTICIPANTID }
     *     
     */
    public FPSPARTICIPANTID getCdtrAgent() {
        return cdtrAgent;
    }

    /**
     * Sets the value of the cdtrAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPSPARTICIPANTID }
     *     
     */
    public void setCdtrAgent(FPSPARTICIPANTID value) {
        this.cdtrAgent = value;
    }

    /**
     * Gets the value of the cdtrNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrNm() {
        return cdtrNm;
    }

    /**
     * Sets the value of the cdtrNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrNm(String value) {
        this.cdtrNm = value;
    }

    /**
     * Gets the value of the cdtrAcTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrAcTp() {
        return cdtrAcTp;
    }

    /**
     * Sets the value of the cdtrAcTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrAcTp(String value) {
        this.cdtrAcTp = value;
    }

    /**
     * Gets the value of the cdtrAcNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrAcNo() {
        return cdtrAcNo;
    }

    /**
     * Sets the value of the cdtrAcNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrAcNo(String value) {
        this.cdtrAcNo = value;
    }

    /**
     * Gets the value of the cdtrOrgIdAnyBIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrOrgIdAnyBIC() {
        return cdtrOrgIdAnyBIC;
    }

    /**
     * Sets the value of the cdtrOrgIdAnyBIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrOrgIdAnyBIC(String value) {
        this.cdtrOrgIdAnyBIC = value;
    }

    /**
     * Gets the value of the cdtrOrgIdOthrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrOrgIdOthrId() {
        return cdtrOrgIdOthrId;
    }

    /**
     * Sets the value of the cdtrOrgIdOthrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrOrgIdOthrId(String value) {
        this.cdtrOrgIdOthrId = value;
    }

    /**
     * Gets the value of the cdtrOrgIdOthrIdSchmeNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrOrgIdOthrIdSchmeNm() {
        return cdtrOrgIdOthrIdSchmeNm;
    }

    /**
     * Sets the value of the cdtrOrgIdOthrIdSchmeNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrOrgIdOthrIdSchmeNm(String value) {
        this.cdtrOrgIdOthrIdSchmeNm = value;
    }

    /**
     * Gets the value of the cdtrOrgIdOthrIssr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrOrgIdOthrIssr() {
        return cdtrOrgIdOthrIssr;
    }

    /**
     * Sets the value of the cdtrOrgIdOthrIssr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrOrgIdOthrIssr(String value) {
        this.cdtrOrgIdOthrIssr = value;
    }

    /**
     * Gets the value of the cdtrPrvtIdOthrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrPrvtIdOthrId() {
        return cdtrPrvtIdOthrId;
    }

    /**
     * Sets the value of the cdtrPrvtIdOthrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrPrvtIdOthrId(String value) {
        this.cdtrPrvtIdOthrId = value;
    }

    /**
     * Gets the value of the cdtrPrvtIdOthrIdSchmeNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrPrvtIdOthrIdSchmeNm() {
        return cdtrPrvtIdOthrIdSchmeNm;
    }

    /**
     * Sets the value of the cdtrPrvtIdOthrIdSchmeNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrPrvtIdOthrIdSchmeNm(String value) {
        this.cdtrPrvtIdOthrIdSchmeNm = value;
    }

    /**
     * Gets the value of the cdtrPrvtIdOthrIssr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrPrvtIdOthrIssr() {
        return cdtrPrvtIdOthrIssr;
    }

    /**
     * Sets the value of the cdtrPrvtIdOthrIssr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrPrvtIdOthrIssr(String value) {
        this.cdtrPrvtIdOthrIssr = value;
    }

    /**
     * Gets the value of the cdtrContPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrContPhone() {
        return cdtrContPhone;
    }

    /**
     * Sets the value of the cdtrContPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrContPhone(String value) {
        this.cdtrContPhone = value;
    }

    /**
     * Gets the value of the cdtrContEmailAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrContEmailAddr() {
        return cdtrContEmailAddr;
    }

    /**
     * Sets the value of the cdtrContEmailAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrContEmailAddr(String value) {
        this.cdtrContEmailAddr = value;
    }

    /**
     * Gets the value of the pytPurpType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPytPurpType() {
        return pytPurpType;
    }

    /**
     * Sets the value of the pytPurpType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPytPurpType(String value) {
        this.pytPurpType = value;
    }

    /**
     * Gets the value of the pytPurp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPytPurp() {
        return pytPurp;
    }

    /**
     * Sets the value of the pytPurp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPytPurp(String value) {
        this.pytPurp = value;
    }

    /**
     * Gets the value of the remInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemInfo() {
        return remInfo;
    }

    /**
     * Sets the value of the remInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemInfo(String value) {
        this.remInfo = value;
    }

}
