//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 02:11:07 ÏÂÎç CST 
//


package com.forms.ffp.adaptor.jaxb.participant.response.head;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HEAD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HEAD">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestID" type="{}Max2NumericText"/>
 *         &lt;element name="TransactionDate" type="{}DateTypeNoSplit"/>
 *         &lt;element name="TransactionTime" type="{}TimeTypeNoSplit"/>
 *         &lt;element name="RequestRefno" type="{}RestrictedNZText_Max30"/>
 *         &lt;element name="AccountingDate" type="{}DateTypeNoSplit" minOccurs="0"/>
 *         &lt;element name="ResponseID" type="{}Max2NumericText"/>
 *         &lt;element name="MessageType" type="{}RestrictedNZText_Max8"/>
 *         &lt;element name="SystemRefno" type="{}RestrictedNZText_Max30"/>
 *         &lt;element name="SystemBeginTIme" type="{}TimeTypeNoSplit" minOccurs="0"/>
 *         &lt;element name="SystemEndTIme" type="{}TimeTypeNoSplit" minOccurs="0"/>
 *         &lt;element name="ResponseRefno" type="{}RestrictedNZText_Max30" minOccurs="0"/>
 *         &lt;element name="ResponseBeginTime" type="{}TimeTypeNoSplit" minOccurs="0"/>
 *         &lt;element name="ResponseEndTime" type="{}TimeTypeNoSplit" minOccurs="0"/>
 *         &lt;element name="ResponseStatus" type="{}Exact1UpperCaseText"/>
 *         &lt;element name="FinalNode" type="{}Exact1UpperCaseText"/>
 *         &lt;element name="SystemMessageCode" type="{}RestrictedNZText_Max8" minOccurs="0"/>
 *         &lt;element name="ResponseMessageCode" type="{}RestrictedFINZText_Max20" minOccurs="0"/>
 *         &lt;element name="ResponseMessage" type="{}RestrictedFINZText_Max1000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HEAD", propOrder = {
    "requestID",
    "transactionDate",
    "transactionTime",
    "requestRefno",
    "accountingDate",
    "responseID",
    "messageType",
    "systemRefno",
    "systemBeginTIme",
    "systemEndTIme",
    "responseRefno",
    "responseBeginTime",
    "responseEndTime",
    "responseStatus",
    "finalNode",
    "systemMessageCode",
    "responseMessageCode",
    "responseMessage"
})
public class HEAD {

    @XmlElement(name = "RequestID", required = true)
    protected String requestID;
    @XmlElement(name = "TransactionDate", required = true)
    protected String transactionDate;
    @XmlElement(name = "TransactionTime", required = true)
    protected String transactionTime;
    @XmlElement(name = "RequestRefno", required = true)
    protected String requestRefno;
    @XmlElement(name = "AccountingDate")
    protected String accountingDate;
    @XmlElement(name = "ResponseID", required = true)
    protected String responseID;
    @XmlElement(name = "MessageType", required = true)
    protected String messageType;
    @XmlElement(name = "SystemRefno", required = true)
    protected String systemRefno;
    @XmlElement(name = "SystemBeginTIme")
    protected String systemBeginTIme;
    @XmlElement(name = "SystemEndTIme")
    protected String systemEndTIme;
    @XmlElement(name = "ResponseRefno")
    protected String responseRefno;
    @XmlElement(name = "ResponseBeginTime")
    protected String responseBeginTime;
    @XmlElement(name = "ResponseEndTime")
    protected String responseEndTime;
    @XmlElement(name = "ResponseStatus", required = true)
    protected String responseStatus;
    @XmlElement(name = "FinalNode", required = true)
    protected String finalNode;
    @XmlElement(name = "SystemMessageCode")
    protected String systemMessageCode;
    @XmlElement(name = "ResponseMessageCode")
    protected String responseMessageCode;
    @XmlElement(name = "ResponseMessage")
    protected String responseMessage;

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the transactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionDate() {
        return transactionDate;
    }

    /**
     * Sets the value of the transactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionDate(String value) {
        this.transactionDate = value;
    }

    /**
     * Gets the value of the transactionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionTime() {
        return transactionTime;
    }

    /**
     * Sets the value of the transactionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionTime(String value) {
        this.transactionTime = value;
    }

    /**
     * Gets the value of the requestRefno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestRefno() {
        return requestRefno;
    }

    /**
     * Sets the value of the requestRefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestRefno(String value) {
        this.requestRefno = value;
    }

    /**
     * Gets the value of the accountingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingDate() {
        return accountingDate;
    }

    /**
     * Sets the value of the accountingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingDate(String value) {
        this.accountingDate = value;
    }

    /**
     * Gets the value of the responseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseID() {
        return responseID;
    }

    /**
     * Sets the value of the responseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseID(String value) {
        this.responseID = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the systemRefno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemRefno() {
        return systemRefno;
    }

    /**
     * Sets the value of the systemRefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemRefno(String value) {
        this.systemRefno = value;
    }

    /**
     * Gets the value of the systemBeginTIme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemBeginTIme() {
        return systemBeginTIme;
    }

    /**
     * Sets the value of the systemBeginTIme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemBeginTIme(String value) {
        this.systemBeginTIme = value;
    }

    /**
     * Gets the value of the systemEndTIme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemEndTIme() {
        return systemEndTIme;
    }

    /**
     * Sets the value of the systemEndTIme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemEndTIme(String value) {
        this.systemEndTIme = value;
    }

    /**
     * Gets the value of the responseRefno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseRefno() {
        return responseRefno;
    }

    /**
     * Sets the value of the responseRefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseRefno(String value) {
        this.responseRefno = value;
    }

    /**
     * Gets the value of the responseBeginTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseBeginTime() {
        return responseBeginTime;
    }

    /**
     * Sets the value of the responseBeginTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseBeginTime(String value) {
        this.responseBeginTime = value;
    }

    /**
     * Gets the value of the responseEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseEndTime() {
        return responseEndTime;
    }

    /**
     * Sets the value of the responseEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseEndTime(String value) {
        this.responseEndTime = value;
    }

    /**
     * Gets the value of the responseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseStatus() {
        return responseStatus;
    }

    /**
     * Sets the value of the responseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseStatus(String value) {
        this.responseStatus = value;
    }

    /**
     * Gets the value of the finalNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalNode() {
        return finalNode;
    }

    /**
     * Sets the value of the finalNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalNode(String value) {
        this.finalNode = value;
    }

    /**
     * Gets the value of the systemMessageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemMessageCode() {
        return systemMessageCode;
    }

    /**
     * Sets the value of the systemMessageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemMessageCode(String value) {
        this.systemMessageCode = value;
    }

    /**
     * Gets the value of the responseMessageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseMessageCode() {
        return responseMessageCode;
    }

    /**
     * Sets the value of the responseMessageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseMessageCode(String value) {
        this.responseMessageCode = value;
    }

    /**
     * Gets the value of the responseMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseMessage() {
        return responseMessage;
    }

    /**
     * Sets the value of the responseMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseMessage(String value) {
        this.responseMessage = value;
    }

}
