//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.10 at 02:39:57 下午 CST 
//


package com.forms.ffp.adaptor.jaxb.participant.response.ffpamr01;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.forms.ffp.adaptor.jaxb.participant.response.BODY;


/**
 * <p>Java class for FFPAMR01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FFPAMR01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UndrlygDtls" type="{}UNDRLYGDTLSTYPE" maxOccurs="10000"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FFPAMR01", propOrder = {
    "undrlygDtls"
})
public class FFPAMR01 extends BODY{

    @XmlElement(name = "UndrlygDtls", required = true)
    protected List<UNDRLYGDTLSTYPE> undrlygDtls;

    /**
     * Gets the value of the undrlygDtls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the undrlygDtls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUndrlygDtls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UNDRLYGDTLSTYPE }
     * 
     * 
     */
    public List<UNDRLYGDTLSTYPE> getUndrlygDtls() {
        if (undrlygDtls == null) {
            undrlygDtls = new ArrayList<UNDRLYGDTLSTYPE>();
        }
        return this.undrlygDtls;
    }

}
