//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.fps_admi_003_001_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Notification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Notification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RcptMdPty" type="{urn:hkicl:fps:xsd:fps.admi.003.001.01}Agent"/>
 *         &lt;element name="RcptMd" type="{urn:hkicl:fps:xsd:fps.admi.003.001.01}ReceiptMode"/>
 *         &lt;element name="SwtchgTm" type="{urn:hkicl:fps:xsd:fps.admi.003.001.01}ISODateTimeType1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Notification", propOrder = {
    "rcptMdPty",
    "rcptMd",
    "swtchgTm"
})
public class Notification {

    @XmlElement(name = "RcptMdPty", required = true)
    protected Agent rcptMdPty;
    @XmlElement(name = "RcptMd", required = true)
    protected ReceiptMode rcptMd;
    @XmlElement(name = "SwtchgTm", required = true)
    protected XMLGregorianCalendar swtchgTm;

    /**
     * Gets the value of the rcptMdPty property.
     * 
     * @return
     *     possible object is
     *     {@link Agent }
     *     
     */
    public Agent getRcptMdPty() {
        return rcptMdPty;
    }

    /**
     * Sets the value of the rcptMdPty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agent }
     *     
     */
    public void setRcptMdPty(Agent value) {
        this.rcptMdPty = value;
    }

    /**
     * Gets the value of the rcptMd property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiptMode }
     *     
     */
    public ReceiptMode getRcptMd() {
        return rcptMd;
    }

    /**
     * Sets the value of the rcptMd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiptMode }
     *     
     */
    public void setRcptMd(ReceiptMode value) {
        this.rcptMd = value;
    }

    /**
     * Gets the value of the swtchgTm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSwtchgTm() {
        return swtchgTm;
    }

    /**
     * Sets the value of the swtchgTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSwtchgTm(XMLGregorianCalendar value) {
        this.swtchgTm = value;
    }

}
