//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.24 at 05:43:53 下午 CST 
//


package com.forms.ffp.adaptor.jaxb.participant.request.ffprro01;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.forms.ffp.adaptor.jaxb.participant.request.BODY;


/**
 * <p>Java class for FFPRRO01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FFPRRO01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SrcRefNm" type="{}RestrictedNZText_Max30"/>
 *         &lt;element name="PymtCatPrps" type="{}UpperCaseNumericText_Exact6"/>
 *         &lt;element name="RtrdSettlDate" type="{}DateTypeNoSplit"/>
 *         &lt;element name="RtrdSettlAmt" type="{}Restricted15Digit2AmountType"/>
 *         &lt;element name="RtrdSettlCcy" type="{}UpperCaseNumericText_Exact3"/>
 *         &lt;element name="RtrdInstrAmt" type="{}Restricted15Digit2AmountType" minOccurs="0"/>
 *         &lt;element name="RtrdInstrCcy" type="{}UpperCaseNumericText_Exact3" minOccurs="0"/>
 *         &lt;element name="RtrdChrgrsAmt" type="{}Restricted15Digit2AmountType" minOccurs="0"/>
 *         &lt;element name="RtrdChrgrsCcy" type="{}UpperCaseNumericText_Exact3" minOccurs="0"/>
 *         &lt;element name="DbtrNm" type="{}RestrictedUnicodeTextMax140"/>
 *         &lt;element name="DbtrAcTp" type="{}UpperCaseNumericText_Exact3"/>
 *         &lt;element name="DbtrAcNo" type="{}RestrictedFINZText_Max34"/>
 *         &lt;element name="DbtrContPhone" type="{}PhoneNumber" minOccurs="0"/>
 *         &lt;element name="DbtrContEmailAddr" type="{}RestrictedFINZText_Max254" minOccurs="0"/>
 *         &lt;element name="RtrRsnInf" type="{}RTRRSNINF"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FFPRRO01", propOrder = {
    "srcRefNm",
    "pymtCatPrps",
    "rtrdSettlDate",
    "rtrdSettlAmt",
    "rtrdSettlCcy",
    "rtrdInstrAmt",
    "rtrdInstrCcy",
    "rtrdChrgrsAmt",
    "rtrdChrgrsCcy",
    "dbtrNm",
    "dbtrAcTp",
    "dbtrAcNo",
    "dbtrContPhone",
    "dbtrContEmailAddr",
    "rtrRsnInf"
})
public class FFPRRO01 extends BODY{

    @XmlElement(name = "SrcRefNm", required = true)
    protected String srcRefNm;
    @XmlElement(name = "PymtCatPrps", required = true)
    protected String pymtCatPrps;
    @XmlElement(name = "RtrdSettlDate", required = true)
    protected String rtrdSettlDate;
    @XmlElement(name = "RtrdSettlAmt", required = true)
    protected BigDecimal rtrdSettlAmt;
    @XmlElement(name = "RtrdSettlCcy", required = true)
    protected String rtrdSettlCcy;
    @XmlElement(name = "RtrdInstrAmt")
    protected BigDecimal rtrdInstrAmt;
    @XmlElement(name = "RtrdInstrCcy")
    protected String rtrdInstrCcy;
    @XmlElement(name = "RtrdChrgrsAmt")
    protected BigDecimal rtrdChrgrsAmt;
    @XmlElement(name = "RtrdChrgrsCcy")
    protected String rtrdChrgrsCcy;
    @XmlElement(name = "DbtrNm", required = true)
    protected String dbtrNm;
    @XmlElement(name = "DbtrAcTp", required = true)
    protected String dbtrAcTp;
    @XmlElement(name = "DbtrAcNo", required = true)
    protected String dbtrAcNo;
    @XmlElement(name = "DbtrContPhone")
    protected String dbtrContPhone;
    @XmlElement(name = "DbtrContEmailAddr")
    protected String dbtrContEmailAddr;
    @XmlElement(name = "RtrRsnInf", required = true)
    protected RTRRSNINF rtrRsnInf;

    /**
     * Gets the value of the srcRefNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcRefNm() {
        return srcRefNm;
    }

    /**
     * Sets the value of the srcRefNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcRefNm(String value) {
        this.srcRefNm = value;
    }

    /**
     * Gets the value of the pymtCatPrps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPymtCatPrps() {
        return pymtCatPrps;
    }

    /**
     * Sets the value of the pymtCatPrps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPymtCatPrps(String value) {
        this.pymtCatPrps = value;
    }

    /**
     * Gets the value of the rtrdSettlDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtrdSettlDate() {
        return rtrdSettlDate;
    }

    /**
     * Sets the value of the rtrdSettlDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtrdSettlDate(String value) {
        this.rtrdSettlDate = value;
    }

    /**
     * Gets the value of the rtrdSettlAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRtrdSettlAmt() {
        return rtrdSettlAmt;
    }

    /**
     * Sets the value of the rtrdSettlAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRtrdSettlAmt(BigDecimal value) {
        this.rtrdSettlAmt = value;
    }

    /**
     * Gets the value of the rtrdSettlCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtrdSettlCcy() {
        return rtrdSettlCcy;
    }

    /**
     * Sets the value of the rtrdSettlCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtrdSettlCcy(String value) {
        this.rtrdSettlCcy = value;
    }

    /**
     * Gets the value of the rtrdInstrAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRtrdInstrAmt() {
        return rtrdInstrAmt;
    }

    /**
     * Sets the value of the rtrdInstrAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRtrdInstrAmt(BigDecimal value) {
        this.rtrdInstrAmt = value;
    }

    /**
     * Gets the value of the rtrdInstrCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtrdInstrCcy() {
        return rtrdInstrCcy;
    }

    /**
     * Sets the value of the rtrdInstrCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtrdInstrCcy(String value) {
        this.rtrdInstrCcy = value;
    }

    /**
     * Gets the value of the rtrdChrgrsAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRtrdChrgrsAmt() {
        return rtrdChrgrsAmt;
    }

    /**
     * Sets the value of the rtrdChrgrsAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRtrdChrgrsAmt(BigDecimal value) {
        this.rtrdChrgrsAmt = value;
    }

    /**
     * Gets the value of the rtrdChrgrsCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtrdChrgrsCcy() {
        return rtrdChrgrsCcy;
    }

    /**
     * Sets the value of the rtrdChrgrsCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtrdChrgrsCcy(String value) {
        this.rtrdChrgrsCcy = value;
    }

    /**
     * Gets the value of the dbtrNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrNm() {
        return dbtrNm;
    }

    /**
     * Sets the value of the dbtrNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrNm(String value) {
        this.dbtrNm = value;
    }

    /**
     * Gets the value of the dbtrAcTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrAcTp() {
        return dbtrAcTp;
    }

    /**
     * Sets the value of the dbtrAcTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrAcTp(String value) {
        this.dbtrAcTp = value;
    }

    /**
     * Gets the value of the dbtrAcNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrAcNo() {
        return dbtrAcNo;
    }

    /**
     * Sets the value of the dbtrAcNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrAcNo(String value) {
        this.dbtrAcNo = value;
    }

    /**
     * Gets the value of the dbtrContPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrContPhone() {
        return dbtrContPhone;
    }

    /**
     * Sets the value of the dbtrContPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrContPhone(String value) {
        this.dbtrContPhone = value;
    }

    /**
     * Gets the value of the dbtrContEmailAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrContEmailAddr() {
        return dbtrContEmailAddr;
    }

    /**
     * Sets the value of the dbtrContEmailAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrContEmailAddr(String value) {
        this.dbtrContEmailAddr = value;
    }

    /**
     * Gets the value of the rtrRsnInf property.
     * 
     * @return
     *     possible object is
     *     {@link RTRRSNINF }
     *     
     */
    public RTRRSNINF getRtrRsnInf() {
        return rtrRsnInf;
    }

    /**
     * Sets the value of the rtrRsnInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTRRSNINF }
     *     
     */
    public void setRtrRsnInf(RTRRSNINF value) {
        this.rtrRsnInf = value;
    }

}
