//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.13 at 02:09:05 下午 CST 
//


package com.forms.ffp.adaptor.jaxb.participant.response.ffpadr04;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CUSTOMERNAMETYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CUSTOMERNAMETYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Lang" type="{}LangType"/>
 *         &lt;element name="FullNm" type="{}RestrictedUnicodeTextMax140"/>
 *         &lt;element name="DispNm" type="{}RestrictedUnicodeTextMax140"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CUSTOMERNAMETYPE",namespace = "http://www.formssi.com/response/ffpadr04", propOrder = {
    "lang",
    "fullNm",
    "dispNm"
})
public class CUSTOMERNAMETYPE {

    @XmlElement(name = "Lang", required = true)
    protected LangType lang;
    @XmlElement(name = "FullNm", required = true)
    protected String fullNm;
    @XmlElement(name = "DispNm", required = true)
    protected String dispNm;

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link LangType }
     *     
     */
    public LangType getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link LangType }
     *     
     */
    public void setLang(LangType value) {
        this.lang = value;
    }

    /**
     * Gets the value of the fullNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullNm() {
        return fullNm;
    }

    /**
     * Sets the value of the fullNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullNm(String value) {
        this.fullNm = value;
    }

    /**
     * Gets the value of the dispNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispNm() {
        return dispNm;
    }

    /**
     * Sets the value of the dispNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispNm(String value) {
        this.dispNm = value;
    }

}
