//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.pacs_008_001_06;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.forms.ffp.adaptor.jaxb.iclfps.pacs_008_001_06 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.forms.ffp.adaptor.jaxb.iclfps.pacs_008_001_06
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice1 }
     * 
     */
    public LocalInstrument2Choice1 createLocalInstrument2Choice1() {
        return new LocalInstrument2Choice1();
    }

    /**
     * Create an instance of {@link CreditTransferTransaction251 }
     * 
     */
    public CreditTransferTransaction251 createCreditTransferTransaction251() {
        return new CreditTransferTransaction251();
    }

    /**
     * Create an instance of {@link PartyIdentification431 }
     * 
     */
    public PartyIdentification431 createPartyIdentification431() {
        return new PartyIdentification431();
    }

    /**
     * Create an instance of {@link ContactDetails21 }
     * 
     */
    public ContactDetails21 createContactDetails21() {
        return new ContactDetails21();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification11 }
     * 
     */
    public GenericOrganisationIdentification11 createGenericOrganisationIdentification11() {
        return new GenericOrganisationIdentification11();
    }

    /**
     * Create an instance of {@link Restricted15Digit2DecimalCurrencyAndAmount }
     * 
     */
    public Restricted15Digit2DecimalCurrencyAndAmount createRestricted15Digit2DecimalCurrencyAndAmount() {
        return new Restricted15Digit2DecimalCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link Charges21 }
     * 
     */
    public Charges21 createCharges21() {
        return new Charges21();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification51 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification51 createBranchAndFinancialInstitutionIdentification51() {
        return new BranchAndFinancialInstitutionIdentification51();
    }

    /**
     * Create an instance of {@link SettlementInstruction41 }
     * 
     */
    public SettlementInstruction41 createSettlementInstruction41() {
        return new SettlementInstruction41();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice1 }
     * 
     */
    public PersonIdentificationSchemeName1Choice1 createPersonIdentificationSchemeName1Choice1() {
        return new PersonIdentificationSchemeName1Choice1();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification81 }
     * 
     */
    public FinancialInstitutionIdentification81 createFinancialInstitutionIdentification81() {
        return new FinancialInstitutionIdentification81();
    }

    /**
     * Create an instance of {@link Party11Choice1 }
     * 
     */
    public Party11Choice1 createParty11Choice1() {
        return new Party11Choice1();
    }

    /**
     * Create an instance of {@link FIToFICustomerCreditTransferV06 }
     * 
     */
    public FIToFICustomerCreditTransferV06 createFIToFICustomerCreditTransferV06() {
        return new FIToFICustomerCreditTransferV06();
    }

    /**
     * Create an instance of {@link PaymentIdentification31 }
     * 
     */
    public PaymentIdentification31 createPaymentIdentification31() {
        return new PaymentIdentification31();
    }

    /**
     * Create an instance of {@link SettlementDateTimeIndication11 }
     * 
     */
    public SettlementDateTimeIndication11 createSettlementDateTimeIndication11() {
        return new SettlementDateTimeIndication11();
    }

    /**
     * Create an instance of {@link GroupHeader701 }
     * 
     */
    public GroupHeader701 createGroupHeader701() {
        return new GroupHeader701();
    }

    /**
     * Create an instance of {@link OrganisationIdentification81 }
     * 
     */
    public OrganisationIdentification81 createOrganisationIdentification81() {
        return new OrganisationIdentification81();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation211 }
     * 
     */
    public PaymentTypeInformation211 createPaymentTypeInformation211() {
        return new PaymentTypeInformation211();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification11 }
     * 
     */
    public GenericPersonIdentification11 createGenericPersonIdentification11() {
        return new GenericPersonIdentification11();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice1 }
     * 
     */
    public AccountSchemeName1Choice1 createAccountSchemeName1Choice1() {
        return new AccountSchemeName1Choice1();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice1 }
     * 
     */
    public CategoryPurpose1Choice1 createCategoryPurpose1Choice1() {
        return new CategoryPurpose1Choice1();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification21 }
     * 
     */
    public ClearingSystemMemberIdentification21 createClearingSystemMemberIdentification21() {
        return new ClearingSystemMemberIdentification21();
    }

    /**
     * Create an instance of {@link CashAccount241 }
     * 
     */
    public CashAccount241 createCashAccount241() {
        return new CashAccount241();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification3Choice1 }
     * 
     */
    public ClearingSystemIdentification3Choice1 createClearingSystemIdentification3Choice1() {
        return new ClearingSystemIdentification3Choice1();
    }

    /**
     * Create an instance of {@link Purpose2Choice1 }
     * 
     */
    public Purpose2Choice1 createPurpose2Choice1() {
        return new Purpose2Choice1();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice1 }
     * 
     */
    public AccountIdentification4Choice1 createAccountIdentification4Choice1() {
        return new AccountIdentification4Choice1();
    }

    /**
     * Create an instance of {@link PersonIdentification51 }
     * 
     */
    public PersonIdentification51 createPersonIdentification51() {
        return new PersonIdentification51();
    }

    /**
     * Create an instance of {@link RemittanceInformation111 }
     * 
     */
    public RemittanceInformation111 createRemittanceInformation111() {
        return new RemittanceInformation111();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice1 }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice1 createOrganisationIdentificationSchemeName1Choice1() {
        return new OrganisationIdentificationSchemeName1Choice1();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification11 }
     * 
     */
    public GenericAccountIdentification11 createGenericAccountIdentification11() {
        return new GenericAccountIdentification11();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
