//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.pain_010_001_05;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Mandate8__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Mandate8__1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MndtId" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.05}RestrictedFINZMax35Text"/>
 *         &lt;element name="MndtReqId" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.05}RestrictedFINZMax35Text"/>
 *         &lt;element name="Ocrncs" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.05}MandateOccurrences4__1" minOccurs="0"/>
 *         &lt;element name="TrckgInd" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.05}TrueFalseIndicator"/>
 *         &lt;element name="ColltnAmt" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.05}Restricted15Digit2DecimalCurrencyAndAmount" minOccurs="0"/>
 *         &lt;element name="MaxAmt" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.05}Restricted15Digit2DecimalCurrencyAndAmount" minOccurs="0"/>
 *         &lt;element name="Cdtr" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.05}PartyIdentification43__1" minOccurs="0"/>
 *         &lt;element name="Dbtr" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.05}PartyIdentification43__1" minOccurs="0"/>
 *         &lt;element name="UltmtDbtr" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.05}PartyIdentification43__1" minOccurs="0"/>
 *         &lt;element name="RfrdDoc" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.05}ReferredMandateDocument1__1" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Mandate8__1", propOrder = {
    "mndtId",
    "mndtReqId",
    "ocrncs",
    "trckgInd",
    "colltnAmt",
    "maxAmt",
    "cdtr",
    "dbtr",
    "ultmtDbtr",
    "rfrdDoc"
})
public class Mandate81 {

    @XmlElement(name = "MndtId", required = true)
    protected String mndtId;
    @XmlElement(name = "MndtReqId", required = true)
    protected String mndtReqId;
    @XmlElement(name = "Ocrncs")
    protected MandateOccurrences41 ocrncs;
    @XmlElement(name = "TrckgInd")
    protected boolean trckgInd;
    @XmlElement(name = "ColltnAmt")
    protected Restricted15Digit2DecimalCurrencyAndAmount colltnAmt;
    @XmlElement(name = "MaxAmt")
    protected Restricted15Digit2DecimalCurrencyAndAmount maxAmt;
    @XmlElement(name = "Cdtr")
    protected PartyIdentification431 cdtr;
    @XmlElement(name = "Dbtr")
    protected PartyIdentification431 dbtr;
    @XmlElement(name = "UltmtDbtr")
    protected PartyIdentification431 ultmtDbtr;
    @XmlElement(name = "RfrdDoc")
    protected ReferredMandateDocument11 rfrdDoc;

    /**
     * Gets the value of the mndtId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMndtId() {
        return mndtId;
    }

    /**
     * Sets the value of the mndtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMndtId(String value) {
        this.mndtId = value;
    }

    /**
     * Gets the value of the mndtReqId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMndtReqId() {
        return mndtReqId;
    }

    /**
     * Sets the value of the mndtReqId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMndtReqId(String value) {
        this.mndtReqId = value;
    }

    /**
     * Gets the value of the ocrncs property.
     * 
     * @return
     *     possible object is
     *     {@link MandateOccurrences41 }
     *     
     */
    public MandateOccurrences41 getOcrncs() {
        return ocrncs;
    }

    /**
     * Sets the value of the ocrncs property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandateOccurrences41 }
     *     
     */
    public void setOcrncs(MandateOccurrences41 value) {
        this.ocrncs = value;
    }

    /**
     * Gets the value of the trckgInd property.
     * 
     */
    public boolean isTrckgInd() {
        return trckgInd;
    }

    /**
     * Sets the value of the trckgInd property.
     * 
     */
    public void setTrckgInd(boolean value) {
        this.trckgInd = value;
    }

    /**
     * Gets the value of the colltnAmt property.
     * 
     * @return
     *     possible object is
     *     {@link Restricted15Digit2DecimalCurrencyAndAmount }
     *     
     */
    public Restricted15Digit2DecimalCurrencyAndAmount getColltnAmt() {
        return colltnAmt;
    }

    /**
     * Sets the value of the colltnAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Restricted15Digit2DecimalCurrencyAndAmount }
     *     
     */
    public void setColltnAmt(Restricted15Digit2DecimalCurrencyAndAmount value) {
        this.colltnAmt = value;
    }

    /**
     * Gets the value of the maxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link Restricted15Digit2DecimalCurrencyAndAmount }
     *     
     */
    public Restricted15Digit2DecimalCurrencyAndAmount getMaxAmt() {
        return maxAmt;
    }

    /**
     * Sets the value of the maxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Restricted15Digit2DecimalCurrencyAndAmount }
     *     
     */
    public void setMaxAmt(Restricted15Digit2DecimalCurrencyAndAmount value) {
        this.maxAmt = value;
    }

    /**
     * Gets the value of the cdtr property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentification431 }
     *     
     */
    public PartyIdentification431 getCdtr() {
        return cdtr;
    }

    /**
     * Sets the value of the cdtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentification431 }
     *     
     */
    public void setCdtr(PartyIdentification431 value) {
        this.cdtr = value;
    }

    /**
     * Gets the value of the dbtr property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentification431 }
     *     
     */
    public PartyIdentification431 getDbtr() {
        return dbtr;
    }

    /**
     * Sets the value of the dbtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentification431 }
     *     
     */
    public void setDbtr(PartyIdentification431 value) {
        this.dbtr = value;
    }

    /**
     * Gets the value of the ultmtDbtr property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentification431 }
     *     
     */
    public PartyIdentification431 getUltmtDbtr() {
        return ultmtDbtr;
    }

    /**
     * Sets the value of the ultmtDbtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentification431 }
     *     
     */
    public void setUltmtDbtr(PartyIdentification431 value) {
        this.ultmtDbtr = value;
    }

    /**
     * Gets the value of the rfrdDoc property.
     * 
     * @return
     *     possible object is
     *     {@link ReferredMandateDocument11 }
     *     
     */
    public ReferredMandateDocument11 getRfrdDoc() {
        return rfrdDoc;
    }

    /**
     * Sets the value of the rfrdDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferredMandateDocument11 }
     *     
     */
    public void setRfrdDoc(ReferredMandateDocument11 value) {
        this.rfrdDoc = value;
    }

}
