//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.fps_cel_001_001_01;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RevokedCertificates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RevokedCertificates">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RevokedCert" type="{urn:hkicl:fps:xsd:fps.cel.001.001.01}RevokedCertificate" maxOccurs="999"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RevokedCertificates", propOrder = {
    "revokedCert"
})
public class RevokedCertificates {

    @XmlElement(name = "RevokedCert", required = true)
    protected List<RevokedCertificate> revokedCert;

    /**
     * Gets the value of the revokedCert property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the revokedCert property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRevokedCert().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RevokedCertificate }
     * 
     * 
     */
    public List<RevokedCertificate> getRevokedCert() {
        if (revokedCert == null) {
            revokedCert = new ArrayList<RevokedCertificate>();
        }
        return this.revokedCert;
    }

}
