//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 02:10:54 ÏÂÎç CST 
//


package com.forms.ffp.adaptor.jaxb.participant.request.head;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HEAD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HEAD">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestID" type="{}Max2NumericText"/>
 *         &lt;element name="TransactionDate" type="{}DateTypeNoSplit"/>
 *         &lt;element name="TransactionTime" type="{}TimeTypeNoSplit"/>
 *         &lt;element name="RequestRefno" type="{}RestrictedNZText_Max30"/>
 *         &lt;element name="AccountingDate" type="{}DateTypeNoSplit" minOccurs="0"/>
 *         &lt;element name="SystemRefno" type="{}RestrictedNZText_Max30" minOccurs="0"/>
 *         &lt;element name="ResponseID" type="{}Max2NumericText"/>
 *         &lt;element name="MessageType" type="{}RestrictedNZText_Max8"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HEAD", propOrder = {
    "requestID",
    "transactionDate",
    "transactionTime",
    "requestRefno",
    "accountingDate",
    "systemRefno",
    "responseID",
    "messageType"
})
public class HEAD {

    @XmlElement(name = "RequestID", required = true)
    protected String requestID;
    @XmlElement(name = "TransactionDate", required = true)
    protected String transactionDate;
    @XmlElement(name = "TransactionTime", required = true)
    protected String transactionTime;
    @XmlElement(name = "RequestRefno", required = true)
    protected String requestRefno;
    @XmlElement(name = "AccountingDate")
    protected String accountingDate;
    @XmlElement(name = "SystemRefno")
    protected String systemRefno;
    @XmlElement(name = "ResponseID", required = true)
    protected String responseID;
    @XmlElement(name = "MessageType", required = true)
    protected String messageType;

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the transactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionDate() {
        return transactionDate;
    }

    /**
     * Sets the value of the transactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionDate(String value) {
        this.transactionDate = value;
    }

    /**
     * Gets the value of the transactionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionTime() {
        return transactionTime;
    }

    /**
     * Sets the value of the transactionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionTime(String value) {
        this.transactionTime = value;
    }

    /**
     * Gets the value of the requestRefno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestRefno() {
        return requestRefno;
    }

    /**
     * Sets the value of the requestRefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestRefno(String value) {
        this.requestRefno = value;
    }

    /**
     * Gets the value of the accountingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingDate() {
        return accountingDate;
    }

    /**
     * Sets the value of the accountingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingDate(String value) {
        this.accountingDate = value;
    }

    /**
     * Gets the value of the systemRefno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemRefno() {
        return systemRefno;
    }

    /**
     * Sets the value of the systemRefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemRefno(String value) {
        this.systemRefno = value;
    }

    /**
     * Gets the value of the responseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseID() {
        return responseID;
    }

    /**
     * Sets the value of the responseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseID(String value) {
        this.responseID = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

}
