//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.23 at 10:41:02 上午 CST 
//


package com.forms.ffp.adaptor.jaxb.participant.request.ffpgf004;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Record complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Record">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SrcRefNm" type="{}RestrictedNZText_Max30"/>
 *         &lt;element name="RsnPrtry" type="{}UpperCaseNumericText_Exact1"/>
 *         &lt;element name="RsnPrtryDesc" type="{}RestrictedFINZText_Max200"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Record", propOrder = {
    "srcRefNm",
    "rsnPrtry",
    "rsnPrtryDesc"
})
public class Record {

    @XmlElement(name = "SrcRefNm", required = true)
    protected String srcRefNm;
    @XmlElement(name = "RsnPrtry", required = true)
    protected String rsnPrtry;
    @XmlElement(name = "RsnPrtryDesc", required = true)
    protected String rsnPrtryDesc;

    /**
     * Gets the value of the srcRefNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcRefNm() {
        return srcRefNm;
    }

    /**
     * Sets the value of the srcRefNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcRefNm(String value) {
        this.srcRefNm = value;
    }

    /**
     * Gets the value of the rsnPrtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsnPrtry() {
        return rsnPrtry;
    }

    /**
     * Sets the value of the rsnPrtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsnPrtry(String value) {
        this.rsnPrtry = value;
    }

    /**
     * Gets the value of the rsnPrtryDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsnPrtryDesc() {
        return rsnPrtryDesc;
    }

    /**
     * Sets the value of the rsnPrtryDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsnPrtryDesc(String value) {
        this.rsnPrtryDesc = value;
    }

}
