//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.fps_cex_001_001_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GroupHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroupHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MsgId" type="{urn:hkicl:fps:xsd:fps.cex.001.001.01}Max35Text"/>
 *         &lt;element name="CreDtTm" type="{urn:hkicl:fps:xsd:fps.cex.001.001.01}ISODateTimeType1"/>
 *         &lt;element name="TotalNewCert" type="{urn:hkicl:fps:xsd:fps.cex.001.001.01}Max6NumericText"/>
 *         &lt;element name="TotalRevokedCert" type="{urn:hkicl:fps:xsd:fps.cex.001.001.01}Max6NumericText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroupHeader", propOrder = {
    "msgId",
    "creDtTm",
    "totalNewCert",
    "totalRevokedCert"
})
public class GroupHeader {

    @XmlElement(name = "MsgId", required = true)
    protected String msgId;
    @XmlElement(name = "CreDtTm", required = true)
    protected XMLGregorianCalendar creDtTm;
    @XmlElement(name = "TotalNewCert", required = true)
    protected String totalNewCert;
    @XmlElement(name = "TotalRevokedCert", required = true)
    protected String totalRevokedCert;

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgId(String value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the creDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreDtTm() {
        return creDtTm;
    }

    /**
     * Sets the value of the creDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreDtTm(XMLGregorianCalendar value) {
        this.creDtTm = value;
    }

    /**
     * Gets the value of the totalNewCert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalNewCert() {
        return totalNewCert;
    }

    /**
     * Sets the value of the totalNewCert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalNewCert(String value) {
        this.totalNewCert = value;
    }

    /**
     * Gets the value of the totalRevokedCert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalRevokedCert() {
        return totalRevokedCert;
    }

    /**
     * Sets the value of the totalRevokedCert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalRevokedCert(String value) {
        this.totalRevokedCert = value;
    }

}
