//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.fps_edda_001_001_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnderlyingCapturedDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnderlyingCapturedDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CptrRslt" type="{urn:hkicl:fps:xsd:fps.edda.001.001.01}CaptureResult"/>
 *         &lt;element name="AdditionalRejectReasonInformation" type="{urn:hkicl:fps:xsd:fps.edda.001.001.01}Max105Text" minOccurs="0"/>
 *         &lt;element name="OrgnlMndt" type="{urn:hkicl:fps:xsd:fps.edda.001.001.01}OriginalMandate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnderlyingCapturedDetails", propOrder = {
    "cptrRslt",
    "additionalRejectReasonInformation",
    "orgnlMndt"
})
public class UnderlyingCapturedDetails {

    @XmlElement(name = "CptrRslt", required = true)
    protected CaptureResult cptrRslt;
    @XmlElement(name = "AdditionalRejectReasonInformation")
    protected String additionalRejectReasonInformation;
    @XmlElement(name = "OrgnlMndt", required = true)
    protected OriginalMandate orgnlMndt;

    /**
     * Gets the value of the cptrRslt property.
     * 
     * @return
     *     possible object is
     *     {@link CaptureResult }
     *     
     */
    public CaptureResult getCptrRslt() {
        return cptrRslt;
    }

    /**
     * Sets the value of the cptrRslt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaptureResult }
     *     
     */
    public void setCptrRslt(CaptureResult value) {
        this.cptrRslt = value;
    }

    /**
     * Gets the value of the additionalRejectReasonInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalRejectReasonInformation() {
        return additionalRejectReasonInformation;
    }

    /**
     * Sets the value of the additionalRejectReasonInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalRejectReasonInformation(String value) {
        this.additionalRejectReasonInformation = value;
    }

    /**
     * Gets the value of the orgnlMndt property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalMandate }
     *     
     */
    public OriginalMandate getOrgnlMndt() {
        return orgnlMndt;
    }

    /**
     * Sets the value of the orgnlMndt property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalMandate }
     *     
     */
    public void setOrgnlMndt(OriginalMandate value) {
        this.orgnlMndt = value;
    }

}
