//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.fps_adrs_007_001_01;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Summary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Summary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CusNm" type="{urn:hkicl:fps:xsd:fps.adrs.007.001.01}CustomerName" maxOccurs="2"/>
 *         &lt;element name="Agt" type="{urn:hkicl:fps:xsd:fps.adrs.007.001.01}Agent"/>
 *         &lt;element name="Dflt" type="{urn:hkicl:fps:xsd:fps.adrs.007.001.01}YesNoIndicator" minOccurs="0"/>
 *         &lt;element name="Purp" type="{urn:hkicl:fps:xsd:fps.adrs.007.001.01}Purpose"/>
 *         &lt;element name="CreDtTm" type="{urn:hkicl:fps:xsd:fps.adrs.007.001.01}DateTimeType1"/>
 *         &lt;element name="LstUpdDtTm" type="{urn:hkicl:fps:xsd:fps.adrs.007.001.01}DateTimeType1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Summary", propOrder = {
    "cusNm",
    "agt",
    "dflt",
    "purp",
    "creDtTm",
    "lstUpdDtTm"
})
public class Summary {

    @XmlElement(name = "CusNm", required = true)
    protected List<CustomerName> cusNm;
    @XmlElement(name = "Agt", required = true)
    protected Agent agt;
    @XmlElement(name = "Dflt")
    protected YesNoIndicator dflt;
    @XmlElement(name = "Purp", required = true)
    protected Purpose purp;
    @XmlElement(name = "CreDtTm", required = true)
    protected String creDtTm;
    @XmlElement(name = "LstUpdDtTm", required = true)
    protected String lstUpdDtTm;

    /**
     * Gets the value of the cusNm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cusNm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCusNm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomerName }
     * 
     * 
     */
    public List<CustomerName> getCusNm() {
        if (cusNm == null) {
            cusNm = new ArrayList<CustomerName>();
        }
        return this.cusNm;
    }

    /**
     * Gets the value of the agt property.
     * 
     * @return
     *     possible object is
     *     {@link Agent }
     *     
     */
    public Agent getAgt() {
        return agt;
    }

    /**
     * Sets the value of the agt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agent }
     *     
     */
    public void setAgt(Agent value) {
        this.agt = value;
    }

    /**
     * Gets the value of the dflt property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoIndicator }
     *     
     */
    public YesNoIndicator getDflt() {
        return dflt;
    }

    /**
     * Sets the value of the dflt property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoIndicator }
     *     
     */
    public void setDflt(YesNoIndicator value) {
        this.dflt = value;
    }

    /**
     * Gets the value of the purp property.
     * 
     * @return
     *     possible object is
     *     {@link Purpose }
     *     
     */
    public Purpose getPurp() {
        return purp;
    }

    /**
     * Sets the value of the purp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Purpose }
     *     
     */
    public void setPurp(Purpose value) {
        this.purp = value;
    }

    /**
     * Gets the value of the creDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreDtTm() {
        return creDtTm;
    }

    /**
     * Sets the value of the creDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreDtTm(String value) {
        this.creDtTm = value;
    }

    /**
     * Gets the value of the lstUpdDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLstUpdDtTm() {
        return lstUpdDtTm;
    }

    /**
     * Sets the value of the lstUpdDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLstUpdDtTm(String value) {
        this.lstUpdDtTm = value;
    }

}
