//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.pacs_003_001_07;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FIToFICustomerDirectDebitV07 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FIToFICustomerDirectDebitV07">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrpHdr" type="{urn:iso:std:iso:20022:tech:xsd:pacs.003.001.07}GroupHeader50__1"/>
 *         &lt;element name="DrctDbtTxInf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.003.001.07}DirectDebitTransactionInformation21__1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FIToFICustomerDirectDebitV07", propOrder = {
    "grpHdr",
    "drctDbtTxInf"
})
public class FIToFICustomerDirectDebitV07 {

    @XmlElement(name = "GrpHdr", required = true)
    protected GroupHeader501 grpHdr;
    @XmlElement(name = "DrctDbtTxInf", required = true)
    protected DirectDebitTransactionInformation211 drctDbtTxInf;

    /**
     * Gets the value of the grpHdr property.
     * 
     * @return
     *     possible object is
     *     {@link GroupHeader501 }
     *     
     */
    public GroupHeader501 getGrpHdr() {
        return grpHdr;
    }

    /**
     * Sets the value of the grpHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupHeader501 }
     *     
     */
    public void setGrpHdr(GroupHeader501 value) {
        this.grpHdr = value;
    }

    /**
     * Gets the value of the drctDbtTxInf property.
     * 
     * @return
     *     possible object is
     *     {@link DirectDebitTransactionInformation211 }
     *     
     */
    public DirectDebitTransactionInformation211 getDrctDbtTxInf() {
        return drctDbtTxInf;
    }

    /**
     * Sets the value of the drctDbtTxInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectDebitTransactionInformation211 }
     *     
     */
    public void setDrctDbtTxInf(DirectDebitTransactionInformation211 value) {
        this.drctDbtTxInf = value;
    }

}
