//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.13 at 02:09:05 下午 CST 
//


package com.forms.ffp.adaptor.jaxb.participant.response.ffpadr03;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.forms.ffp.adaptor.jaxb.participant.response.BODY;


/**
 * <p>Java class for FFPADR03 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FFPADR03">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SrcRefNm" type="{}RestrictedFINZText_Max30"/>
 *         &lt;element name="Sts" type="{}Exact1UpperCaseText"/>
 *         &lt;element name="RjCd" type="{}RestrictedNZText_Max8" minOccurs="0"/>
 *         &lt;element name="ProxyId" type="{}RestrictedFINZText_Max34"/>
 *         &lt;element name="ProxyIdTp" type="{}UpperCaseNumericText_Exact4"/>
 *         &lt;element name="NoOfAdr" type="{}Noofaddress"/>
 *         &lt;element name="Smry" type="{}SUMMARYTYPE" maxOccurs="5000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FFPADR03", propOrder = {
    "srcRefNm",
    "sts",
    "rjCd",
    "proxyId",
    "proxyIdTp",
    "noOfAdr",
    "smry"
})
public class FFPADR03 extends BODY{

    @XmlElement(name = "SrcRefNm", required = true)
    protected String srcRefNm;
    @XmlElement(name = "Sts", required = true)
    protected String sts;
    @XmlElement(name = "RjCd")
    protected String rjCd;
    @XmlElement(name = "ProxyId", required = true)
    protected String proxyId;
    @XmlElement(name = "ProxyIdTp", required = true)
    protected String proxyIdTp;
    @XmlElement(name = "NoOfAdr", required = true)
    protected String noOfAdr;
    @XmlElement(name = "Smry")
    protected List<SUMMARYTYPE> smry;

    /**
     * Gets the value of the srcRefNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcRefNm() {
        return srcRefNm;
    }

    /**
     * Sets the value of the srcRefNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcRefNm(String value) {
        this.srcRefNm = value;
    }

    /**
     * Gets the value of the sts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSts() {
        return sts;
    }

    /**
     * Sets the value of the sts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSts(String value) {
        this.sts = value;
    }

    /**
     * Gets the value of the rjCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRjCd() {
        return rjCd;
    }

    /**
     * Sets the value of the rjCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRjCd(String value) {
        this.rjCd = value;
    }

    /**
     * Gets the value of the proxyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxyId() {
        return proxyId;
    }

    /**
     * Sets the value of the proxyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxyId(String value) {
        this.proxyId = value;
    }

    /**
     * Gets the value of the proxyIdTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxyIdTp() {
        return proxyIdTp;
    }

    /**
     * Sets the value of the proxyIdTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxyIdTp(String value) {
        this.proxyIdTp = value;
    }

    /**
     * Gets the value of the noOfAdr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfAdr() {
        return noOfAdr;
    }

    /**
     * Sets the value of the noOfAdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfAdr(String value) {
        this.noOfAdr = value;
    }

    /**
     * Gets the value of the smry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSmry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SUMMARYTYPE }
     * 
     * 
     */
    public List<SUMMARYTYPE> getSmry() {
        if (smry == null) {
            smry = new ArrayList<SUMMARYTYPE>();
        }
        return this.smry;
    }

}
