//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.13 at 02:09:05 下午 CST 
//


package com.forms.ffp.adaptor.jaxb.participant.response.ffpadr04;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ADDRESSINGSCHEMETYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ADDRESSINGSCHEMETYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sts" type="{}Exact4UpperCaseText"/>
 *         &lt;element name="RsnInfCd" type="{}UpperCaseNumericText_Exact4" minOccurs="0"/>
 *         &lt;element name="ProxyId" type="{}RestrictedFINZText_Max34"/>
 *         &lt;element name="ProxyIdTp" type="{}UpperCaseNumericText_Exact4"/>
 *         &lt;element name="PurpCd" type="{}UpperCaseNumericText_Exact4"/>
 *         &lt;element name="RsltCusNm" type="{}CUSTOMERNAMETYPE" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="RsltCusId" type="{}RestrictedFINZText_Max34" minOccurs="0"/>
 *         &lt;element name="MmbId" type="{}MmbIdType" minOccurs="0"/>
 *         &lt;element name="RsltCusTp" type="{}UpperCaseNumericText_Exact4" minOccurs="0"/>
 *         &lt;element name="SupOpCd" type="{}UpperCaseNumericText_Exact4" maxOccurs="2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ADDRESSINGSCHEMETYPE",namespace = "http://www.formssi.com/response/ffpadr04", propOrder = {
    "sts",
    "rsnInfCd",
    "proxyId",
    "proxyIdTp",
    "purpCd",
    "rsltCusNm",
    "rsltCusId",
    "mmbId",
    "rsltCusTp",
    "supOpCd"
})
public class ADDRESSINGSCHEMETYPE {

    @XmlElement(name = "Sts", required = true)
    protected String sts;
    @XmlElement(name = "RsnInfCd")
    protected String rsnInfCd;
    @XmlElement(name = "ProxyId", required = true)
    protected String proxyId;
    @XmlElement(name = "ProxyIdTp", required = true)
    protected String proxyIdTp;
    @XmlElement(name = "PurpCd", required = true)
    protected String purpCd;
    @XmlElement(name = "RsltCusNm")
    protected List<CUSTOMERNAMETYPE> rsltCusNm;
    @XmlElement(name = "RsltCusId")
    protected String rsltCusId;
    @XmlElement(name = "MmbId")
    protected String mmbId;
    @XmlElement(name = "RsltCusTp")
    protected String rsltCusTp;
    @XmlElement(name = "SupOpCd")
    protected List<String> supOpCd;

    /**
     * Gets the value of the sts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSts() {
        return sts;
    }

    /**
     * Sets the value of the sts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSts(String value) {
        this.sts = value;
    }

    /**
     * Gets the value of the rsnInfCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsnInfCd() {
        return rsnInfCd;
    }

    /**
     * Sets the value of the rsnInfCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsnInfCd(String value) {
        this.rsnInfCd = value;
    }

    /**
     * Gets the value of the proxyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxyId() {
        return proxyId;
    }

    /**
     * Sets the value of the proxyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxyId(String value) {
        this.proxyId = value;
    }

    /**
     * Gets the value of the proxyIdTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxyIdTp() {
        return proxyIdTp;
    }

    /**
     * Sets the value of the proxyIdTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxyIdTp(String value) {
        this.proxyIdTp = value;
    }

    /**
     * Gets the value of the purpCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpCd() {
        return purpCd;
    }

    /**
     * Sets the value of the purpCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpCd(String value) {
        this.purpCd = value;
    }

    /**
     * Gets the value of the rsltCusNm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rsltCusNm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRsltCusNm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CUSTOMERNAMETYPE }
     * 
     * 
     */
    public List<CUSTOMERNAMETYPE> getRsltCusNm() {
        if (rsltCusNm == null) {
            rsltCusNm = new ArrayList<CUSTOMERNAMETYPE>();
        }
        return this.rsltCusNm;
    }

    /**
     * Gets the value of the rsltCusId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsltCusId() {
        return rsltCusId;
    }

    /**
     * Sets the value of the rsltCusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsltCusId(String value) {
        this.rsltCusId = value;
    }

    /**
     * Gets the value of the mmbId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMmbId() {
        return mmbId;
    }

    /**
     * Sets the value of the mmbId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMmbId(String value) {
        this.mmbId = value;
    }

    /**
     * Gets the value of the rsltCusTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsltCusTp() {
        return rsltCusTp;
    }

    /**
     * Sets the value of the rsltCusTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsltCusTp(String value) {
        this.rsltCusTp = value;
    }

    /**
     * Gets the value of the supOpCd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supOpCd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupOpCd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSupOpCd() {
        if (supOpCd == null) {
            supOpCd = new ArrayList<String>();
        }
        return this.supOpCd;
    }

}
