//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.21 at 03:49:51 下午 CST 
//


package com.forms.ffp.adaptor.jaxb.participant.request.ffprri01;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.forms.ffp.adaptor.jaxb.participant.request.BODY;


/**
 * <p>Java class for FFPRRI01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FFPRRI01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SrcRefNm" type="{}RestrictedNZText_Max30"/>
 *         &lt;element name="PymtCatPrps" type="{}UpperCaseNumericText_Exact6"/>
 *         &lt;element name="RtrdSettlDate" type="{}DateTypeNoSplit"/>
 *         &lt;element name="RtrdSettlAmt" type="{}Restricted15Digit2AmountType"/>
 *         &lt;element name="RtrdSettlCcy" type="{}UpperCaseNumericText_Exact3"/>
 *         &lt;element name="RtrdInstrAmt" type="{}Restricted15Digit2AmountType" minOccurs="0"/>
 *         &lt;element name="RtrdInstrCcy" type="{}UpperCaseNumericText_Exact3" minOccurs="0"/>
 *         &lt;element name="RtrdChrgrsAmt" type="{}Restricted15Digit2AmountType" minOccurs="0"/>
 *         &lt;element name="RtrdChrgrsCcy" type="{}UpperCaseNumericText_Exact3" minOccurs="0"/>
 *         &lt;element name="CdtrNm" type="{}RestrictedUnicodeTextMax140"/>
 *         &lt;element name="CdtrAcTp" type="{}UpperCaseNumericText_Exact3"/>
 *         &lt;element name="CdtrAcNo" type="{}RestrictedFINZText_Max34"/>
 *         &lt;element name="CdtrContPhone" type="{}PhoneNumber" minOccurs="0"/>
 *         &lt;element name="CdtrContEmailAddr" type="{}RestrictedFINZText_Max254" minOccurs="0"/>
 *         &lt;element name="RtrRsnInf" type="{}RTRRSNINF"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FFPRRI01", propOrder = {
    "srcRefNm",
    "pymtCatPrps",
    "rtrdSettlDate",
    "rtrdSettlAmt",
    "rtrdSettlCcy",
    "rtrdInstrAmt",
    "rtrdInstrCcy",
    "rtrdChrgrsAmt",
    "rtrdChrgrsCcy",
    "cdtrNm",
    "cdtrAcTp",
    "cdtrAcNo",
    "cdtrContPhone",
    "cdtrContEmailAddr",
    "rtrRsnInf"
})
public class FFPRRI01 extends BODY{

    @XmlElement(name = "SrcRefNm", required = true)
    protected String srcRefNm;
    @XmlElement(name = "PymtCatPrps", required = true)
    protected String pymtCatPrps;
    @XmlElement(name = "RtrdSettlDate", required = true)
    protected String rtrdSettlDate;
    @XmlElement(name = "RtrdSettlAmt", required = true)
    protected BigDecimal rtrdSettlAmt;
    @XmlElement(name = "RtrdSettlCcy", required = true)
    protected String rtrdSettlCcy;
    @XmlElement(name = "RtrdInstrAmt")
    protected BigDecimal rtrdInstrAmt;
    @XmlElement(name = "RtrdInstrCcy")
    protected String rtrdInstrCcy;
    @XmlElement(name = "RtrdChrgrsAmt")
    protected BigDecimal rtrdChrgrsAmt;
    @XmlElement(name = "RtrdChrgrsCcy")
    protected String rtrdChrgrsCcy;
    @XmlElement(name = "CdtrNm", required = true)
    protected String cdtrNm;
    @XmlElement(name = "CdtrAcTp", required = true)
    protected String cdtrAcTp;
    @XmlElement(name = "CdtrAcNo", required = true)
    protected String cdtrAcNo;
    @XmlElement(name = "CdtrContPhone")
    protected String cdtrContPhone;
    @XmlElement(name = "CdtrContEmailAddr")
    protected String cdtrContEmailAddr;
    @XmlElement(name = "RtrRsnInf", required = true)
    protected RTRRSNINF rtrRsnInf;

    /**
     * Gets the value of the srcRefNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcRefNm() {
        return srcRefNm;
    }

    /**
     * Sets the value of the srcRefNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcRefNm(String value) {
        this.srcRefNm = value;
    }

    /**
     * Gets the value of the pymtCatPrps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPymtCatPrps() {
        return pymtCatPrps;
    }

    /**
     * Sets the value of the pymtCatPrps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPymtCatPrps(String value) {
        this.pymtCatPrps = value;
    }

    /**
     * Gets the value of the rtrdSettlDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtrdSettlDate() {
        return rtrdSettlDate;
    }

    /**
     * Sets the value of the rtrdSettlDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtrdSettlDate(String value) {
        this.rtrdSettlDate = value;
    }

    /**
     * Gets the value of the rtrdSettlAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRtrdSettlAmt() {
        return rtrdSettlAmt;
    }

    /**
     * Sets the value of the rtrdSettlAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRtrdSettlAmt(BigDecimal value) {
        this.rtrdSettlAmt = value;
    }

    /**
     * Gets the value of the rtrdSettlCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtrdSettlCcy() {
        return rtrdSettlCcy;
    }

    /**
     * Sets the value of the rtrdSettlCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtrdSettlCcy(String value) {
        this.rtrdSettlCcy = value;
    }

    /**
     * Gets the value of the rtrdInstrAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRtrdInstrAmt() {
        return rtrdInstrAmt;
    }

    /**
     * Sets the value of the rtrdInstrAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRtrdInstrAmt(BigDecimal value) {
        this.rtrdInstrAmt = value;
    }

    /**
     * Gets the value of the rtrdInstrCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtrdInstrCcy() {
        return rtrdInstrCcy;
    }

    /**
     * Sets the value of the rtrdInstrCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtrdInstrCcy(String value) {
        this.rtrdInstrCcy = value;
    }

    /**
     * Gets the value of the rtrdChrgrsAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRtrdChrgrsAmt() {
        return rtrdChrgrsAmt;
    }

    /**
     * Sets the value of the rtrdChrgrsAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRtrdChrgrsAmt(BigDecimal value) {
        this.rtrdChrgrsAmt = value;
    }

    /**
     * Gets the value of the rtrdChrgrsCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtrdChrgrsCcy() {
        return rtrdChrgrsCcy;
    }

    /**
     * Sets the value of the rtrdChrgrsCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtrdChrgrsCcy(String value) {
        this.rtrdChrgrsCcy = value;
    }

    /**
     * Gets the value of the cdtrNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrNm() {
        return cdtrNm;
    }

    /**
     * Sets the value of the cdtrNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrNm(String value) {
        this.cdtrNm = value;
    }

    /**
     * Gets the value of the cdtrAcTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrAcTp() {
        return cdtrAcTp;
    }

    /**
     * Sets the value of the cdtrAcTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrAcTp(String value) {
        this.cdtrAcTp = value;
    }

    /**
     * Gets the value of the cdtrAcNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrAcNo() {
        return cdtrAcNo;
    }

    /**
     * Sets the value of the cdtrAcNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrAcNo(String value) {
        this.cdtrAcNo = value;
    }

    /**
     * Gets the value of the cdtrContPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrContPhone() {
        return cdtrContPhone;
    }

    /**
     * Sets the value of the cdtrContPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrContPhone(String value) {
        this.cdtrContPhone = value;
    }

    /**
     * Gets the value of the cdtrContEmailAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrContEmailAddr() {
        return cdtrContEmailAddr;
    }

    /**
     * Sets the value of the cdtrContEmailAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrContEmailAddr(String value) {
        this.cdtrContEmailAddr = value;
    }

    /**
     * Gets the value of the rtrRsnInf property.
     * 
     * @return
     *     possible object is
     *     {@link RTRRSNINF }
     *     
     */
    public RTRRSNINF getRtrRsnInf() {
        return rtrRsnInf;
    }

    /**
     * Sets the value of the rtrRsnInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTRRSNINF }
     *     
     */
    public void setRtrRsnInf(RTRRSNINF value) {
        this.rtrRsnInf = value;
    }

}
