//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.fps_cex_002_001_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RejectedCertificate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RejectedCertificate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RjctCd" type="{urn:hkicl:fps:xsd:fps.cex.002.001.01}Max2NumericText"/>
 *         &lt;element name="eCert" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RejectedCertificate", propOrder = {
    "rjctCd",
    "eCert"
})
public class RejectedCertificate {

    @XmlElement(name = "RjctCd", required = true)
    protected String rjctCd;
    @XmlElement(required = true)
    protected byte[] eCert;

    /**
     * Gets the value of the rjctCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRjctCd() {
        return rjctCd;
    }

    /**
     * Sets the value of the rjctCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRjctCd(String value) {
        this.rjctCd = value;
    }

    /**
     * Gets the value of the eCert property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getECert() {
        return eCert;
    }

    /**
     * Sets the value of the eCert property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setECert(byte[] value) {
        this.eCert = ((byte[]) value);
    }

}
