###################################################################
# CibSetEnv.sh
###################################################################

#JAVA_VM should be set in AIX user profile
#JAVA_VM="/usr/java5_32/jre/bin"
#export $JAVA_VM
#$JAVA_VM/java -version

JAR_DIR="$CIB_BATCH_ROOT/runjar"
JAR_FILE="$JAR_DIR/CIB_BATCH.jar"
echo "JAR_FILE: $JAR_FILE"

LOG_DIR="$CIB_BATCH_LOG/log"
echo " in setenv : LOG_DIR: $LOG_DIR"

#
LIB_DIR="$CIB_BATCH_ROOT/lib"
LIB_FILE="$LIB_FILE:$LIB_DIR/activation.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/am5-xmlrpc-api.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cglib-full-2.0.1.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_adaptor.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_define.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_errhandle.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_framework.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_java.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_jaxb.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_logger.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_mail.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_persistence.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_twofa.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_util.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_authen.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-beanutils-1.8.0.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-beanutils.jar"

#online Tx Related
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-chain-1.2.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-codec-1.3.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-collections.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-dbcp.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-dbutils-1.3-javadoc.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-dbutils-1.3-sources.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-dbutils-1.3.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-digester-1.8.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-digester-2.0.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-fileupload-1.2.2.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-io-2.0.1.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-lang-2.4.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-lang-2.1.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-logging-1.1.1.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-net-1.4.1.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/commons-pool-1.4.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/db2jcc.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/db2jcc_javax.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/db2jcc_license_cu.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/DcmPKIEnable.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/DcmPKILib.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/dom4j-1.4.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/ehcache-0.7.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/hibernate2.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/hibernate3.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/IBD_COMMON.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/itext-2.0.0.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/jaxb-api.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/jaxb-impl.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/jaxb-impl1.0.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/jaxb-libs.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/jaxb-xjc.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/js.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/jsr173_1.0_api.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/jxl.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/log4j-1.2.13.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/mail.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/MCF_COMMON.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/MCF_CLIENT.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/MCF_SERVICE.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/MCF_SERVICE_CLIENT.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/MCF_WEB.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/odmg-3.0.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/relaxngDatatype.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/serviceapi5-xmlrpc.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/sitemesh-2.2.1.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/cib_stax.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/ws-commons-util-1.0.2.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/xmlrpc-client-3.1.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/xmlrpc-common-3.1.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/xsdlib.jar"
LIB_FILE="$LIB_FILE:$CIB_WAS_LIB"

LIB_FILE="$LIB_FILE:$CIB_ISB_JAR/asm.jar"
LIB_FILE="$LIB_FILE:$CIB_ISB_JAR/com.ibm.mq.jar"
LIB_FILE="$LIB_FILE:$ISB_LIB_JAR"
LIB_FILE="$LIB_FILE:$ISB_JAR"
LIB_FILE="$LIB_FILE:$CIB_ISB_JAR/j2ee.jar"
LIB_FILE="$LIB_FILE:$CIB_ISB_JAR/xstream-1.2.2.jar"

LIB_FILE="$LIB_FILE:$LIB_DIR/icu4j-4_8.jar"
LIB_FILE="$LIB_FILE:$LIB_DIR/icu4j-charset-4_8.jar"

LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/job/common"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/job/advice/msg"
LIB_FILE="$LIB_FILE:$CIB_BATCH_CONFINFO"

LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/broadcast"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/charset"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/config"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/CVSROOT"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/ecert"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/email"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/errMsg"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/font"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/ibd"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/mcf_batch"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/mcf"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/menu"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/persistence"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/roleMapping"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/serviceLabel"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/serviceMapping"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/twoFA"
LIB_FILE="$LIB_FILE:$CIB_BATCH_ROOT/conf/cib_resources/upload"


LIB_FILE="$LIB_FILE:$JAR_DIR"
echo "LIB_FILE: $LIB_FILE"