//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.camt_054_001_06;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.forms.ffp.adaptor.jaxb.iclfps.camt_054_001_06 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.054.001.06", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.forms.ffp.adaptor.jaxb.iclfps.camt_054_001_06
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification11 }
     * 
     */
    public GenericOrganisationIdentification11 createGenericOrganisationIdentification11() {
        return new GenericOrganisationIdentification11();
    }

    /**
     * Create an instance of {@link RemittanceInformation111 }
     * 
     */
    public RemittanceInformation111 createRemittanceInformation111() {
        return new RemittanceInformation111();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification21 }
     * 
     */
    public ClearingSystemMemberIdentification21 createClearingSystemMemberIdentification21() {
        return new ClearingSystemMemberIdentification21();
    }

    /**
     * Create an instance of {@link ReturnReason5Choice1 }
     * 
     */
    public ReturnReason5Choice1 createReturnReason5Choice1() {
        return new ReturnReason5Choice1();
    }

    /**
     * Create an instance of {@link PersonIdentification51 }
     * 
     */
    public PersonIdentification51 createPersonIdentification51() {
        return new PersonIdentification51();
    }

    /**
     * Create an instance of {@link BankTransactionCodeStructure41 }
     * 
     */
    public BankTransactionCodeStructure41 createBankTransactionCodeStructure41() {
        return new BankTransactionCodeStructure41();
    }

    /**
     * Create an instance of {@link TransactionAgents31 }
     * 
     */
    public TransactionAgents31 createTransactionAgents31() {
        return new TransactionAgents31();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice1 }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice1 createOrganisationIdentificationSchemeName1Choice1() {
        return new OrganisationIdentificationSchemeName1Choice1();
    }

    /**
     * Create an instance of {@link ReportEntry81 }
     * 
     */
    public ReportEntry81 createReportEntry81() {
        return new ReportEntry81();
    }

    /**
     * Create an instance of {@link PartyIdentification431 }
     * 
     */
    public PartyIdentification431 createPartyIdentification431() {
        return new PartyIdentification431();
    }

    /**
     * Create an instance of {@link BankToCustomerDebitCreditNotificationV06 }
     * 
     */
    public BankToCustomerDebitCreditNotificationV06 createBankToCustomerDebitCreditNotificationV06() {
        return new BankToCustomerDebitCreditNotificationV06();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice1 }
     * 
     */
    public PersonIdentificationSchemeName1Choice1 createPersonIdentificationSchemeName1Choice1() {
        return new PersonIdentificationSchemeName1Choice1();
    }

    /**
     * Create an instance of {@link EntryTransaction81 }
     * 
     */
    public EntryTransaction81 createEntryTransaction81() {
        return new EntryTransaction81();
    }

    /**
     * Create an instance of {@link AccountNotification121 }
     * 
     */
    public AccountNotification121 createAccountNotification121() {
        return new AccountNotification121();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice2 }
     * 
     */
    public AccountIdentification4Choice2 createAccountIdentification4Choice2() {
        return new AccountIdentification4Choice2();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification51 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification51 createBranchAndFinancialInstitutionIdentification51() {
        return new BranchAndFinancialInstitutionIdentification51();
    }

    /**
     * Create an instance of {@link CashAccount241 }
     * 
     */
    public CashAccount241 createCashAccount241() {
        return new CashAccount241();
    }

    /**
     * Create an instance of {@link Restricted15Digit2DecimalCurrencyAndAmount }
     * 
     */
    public Restricted15Digit2DecimalCurrencyAndAmount createRestricted15Digit2DecimalCurrencyAndAmount() {
        return new Restricted15Digit2DecimalCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link Charges41 }
     * 
     */
    public Charges41 createCharges41() {
        return new Charges41();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification11 }
     * 
     */
    public GenericAccountIdentification11 createGenericAccountIdentification11() {
        return new GenericAccountIdentification11();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice1 }
     * 
     */
    public AccountSchemeName1Choice1 createAccountSchemeName1Choice1() {
        return new AccountSchemeName1Choice1();
    }

    /**
     * Create an instance of {@link EntryDetails71 }
     * 
     */
    public EntryDetails71 createEntryDetails71() {
        return new EntryDetails71();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice1 }
     * 
     */
    public CashAccountType2Choice1 createCashAccountType2Choice1() {
        return new CashAccountType2Choice1();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification11 }
     * 
     */
    public GenericPersonIdentification11 createGenericPersonIdentification11() {
        return new GenericPersonIdentification11();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification12 }
     * 
     */
    public GenericAccountIdentification12 createGenericAccountIdentification12() {
        return new GenericAccountIdentification12();
    }

    /**
     * Create an instance of {@link Purpose2Choice1 }
     * 
     */
    public Purpose2Choice1 createPurpose2Choice1() {
        return new Purpose2Choice1();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice1 }
     * 
     */
    public AccountIdentification4Choice1 createAccountIdentification4Choice1() {
        return new AccountIdentification4Choice1();
    }

    /**
     * Create an instance of {@link ContactDetails21 }
     * 
     */
    public ContactDetails21 createContactDetails21() {
        return new ContactDetails21();
    }

    /**
     * Create an instance of {@link CashAccount251 }
     * 
     */
    public CashAccount251 createCashAccount251() {
        return new CashAccount251();
    }

    /**
     * Create an instance of {@link TransactionDates21 }
     * 
     */
    public TransactionDates21 createTransactionDates21() {
        return new TransactionDates21();
    }

    /**
     * Create an instance of {@link Party11Choice1 }
     * 
     */
    public Party11Choice1 createParty11Choice1() {
        return new Party11Choice1();
    }

    /**
     * Create an instance of {@link TransactionParties31 }
     * 
     */
    public TransactionParties31 createTransactionParties31() {
        return new TransactionParties31();
    }

    /**
     * Create an instance of {@link GroupHeader581 }
     * 
     */
    public GroupHeader581 createGroupHeader581() {
        return new GroupHeader581();
    }

    /**
     * Create an instance of {@link TransactionReferences31 }
     * 
     */
    public TransactionReferences31 createTransactionReferences31() {
        return new TransactionReferences31();
    }

    /**
     * Create an instance of {@link PaymentReturnReason21 }
     * 
     */
    public PaymentReturnReason21 createPaymentReturnReason21() {
        return new PaymentReturnReason21();
    }

    /**
     * Create an instance of {@link OrganisationIdentification81 }
     * 
     */
    public OrganisationIdentification81 createOrganisationIdentification81() {
        return new OrganisationIdentification81();
    }

    /**
     * Create an instance of {@link ChargesRecord21 }
     * 
     */
    public ChargesRecord21 createChargesRecord21() {
        return new ChargesRecord21();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification81 }
     * 
     */
    public FinancialInstitutionIdentification81 createFinancialInstitutionIdentification81() {
        return new FinancialInstitutionIdentification81();
    }

    /**
     * Create an instance of {@link ProprietaryBankTransactionCodeStructure11 }
     * 
     */
    public ProprietaryBankTransactionCodeStructure11 createProprietaryBankTransactionCodeStructure11() {
        return new ProprietaryBankTransactionCodeStructure11();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.054.001.06", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
