//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.fps_adrs_006_001_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressingScheme complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressingScheme">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AdrReqId" type="{urn:hkicl:fps:xsd:fps.adrs.006.001.01}Max35Text"/>
 *         &lt;element name="Id" type="{urn:hkicl:fps:xsd:fps.adrs.006.001.01}Max34Text"/>
 *         &lt;element name="Tp" type="{urn:hkicl:fps:xsd:fps.adrs.006.001.01}ProxyIDType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressingScheme", propOrder = {
    "adrReqId",
    "id",
    "tp"
})
public class AddressingScheme {

    @XmlElement(name = "AdrReqId", required = true)
    protected String adrReqId;
    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "Tp", required = true)
    protected ProxyIDType tp;

    /**
     * Gets the value of the adrReqId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdrReqId() {
        return adrReqId;
    }

    /**
     * Sets the value of the adrReqId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdrReqId(String value) {
        this.adrReqId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the tp property.
     * 
     * @return
     *     possible object is
     *     {@link ProxyIDType }
     *     
     */
    public ProxyIDType getTp() {
        return tp;
    }

    /**
     * Sets the value of the tp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxyIDType }
     *     
     */
    public void setTp(ProxyIDType value) {
        this.tp = value;
    }

}
