//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.pain_012_001_05;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcceptanceResult6__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcceptanceResult6__1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Accptd" type="{urn:iso:std:iso:20022:tech:xsd:pain.012.001.05}YesNoIndicator"/>
 *         &lt;element name="RjctRsn" type="{urn:iso:std:iso:20022:tech:xsd:pain.012.001.05}MandateReason1Choice__1" minOccurs="0"/>
 *         &lt;element name="AddtlRjctRsnInf" type="{urn:iso:std:iso:20022:tech:xsd:pain.012.001.05}RestrictedFINZMax105Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcceptanceResult6__1", propOrder = {
    "accptd",
    "rjctRsn",
    "addtlRjctRsnInf"
})
public class AcceptanceResult61 {

    @XmlElement(name = "Accptd")
    protected boolean accptd;
    @XmlElement(name = "RjctRsn")
    protected MandateReason1Choice1 rjctRsn;
    @XmlElement(name = "AddtlRjctRsnInf")
    protected String addtlRjctRsnInf;

    /**
     * Gets the value of the accptd property.
     * 
     */
    public boolean isAccptd() {
        return accptd;
    }

    /**
     * Sets the value of the accptd property.
     * 
     */
    public void setAccptd(boolean value) {
        this.accptd = value;
    }

    /**
     * Gets the value of the rjctRsn property.
     * 
     * @return
     *     possible object is
     *     {@link MandateReason1Choice1 }
     *     
     */
    public MandateReason1Choice1 getRjctRsn() {
        return rjctRsn;
    }

    /**
     * Sets the value of the rjctRsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandateReason1Choice1 }
     *     
     */
    public void setRjctRsn(MandateReason1Choice1 value) {
        this.rjctRsn = value;
    }

    /**
     * Gets the value of the addtlRjctRsnInf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddtlRjctRsnInf() {
        return addtlRjctRsnInf;
    }

    /**
     * Sets the value of the addtlRjctRsnInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddtlRjctRsnInf(String value) {
        this.addtlRjctRsnInf = value;
    }

}
