//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.pain_012_001_05;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FPSMandateAcceptanceRejectReasonCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FPSMandateAcceptanceRejectReasonCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DTAC01"/>
 *     &lt;enumeration value="DTAC02"/>
 *     &lt;enumeration value="DTAC03"/>
 *     &lt;enumeration value="DTAC04"/>
 *     &lt;enumeration value="DTAC05"/>
 *     &lt;enumeration value="DTAC06"/>
 *     &lt;enumeration value="DTAC07"/>
 *     &lt;enumeration value="DTAC08"/>
 *     &lt;enumeration value="DTID01"/>
 *     &lt;enumeration value="DTID02"/>
 *     &lt;enumeration value="DTID03"/>
 *     &lt;enumeration value="DTID04"/>
 *     &lt;enumeration value="DTID05"/>
 *     &lt;enumeration value="DTID06"/>
 *     &lt;enumeration value="DTRF01"/>
 *     &lt;enumeration value="CTAC01"/>
 *     &lt;enumeration value="TODT01"/>
 *     &lt;enumeration value="MNDT01"/>
 *     &lt;enumeration value="MNDT02"/>
 *     &lt;enumeration value="MNDT03"/>
 *     &lt;enumeration value="MNDT04"/>
 *     &lt;enumeration value="OTHERS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FPSMandateAcceptanceRejectReasonCode")
@XmlEnum
public enum FPSMandateAcceptanceRejectReasonCode {

    @XmlEnumValue("DTAC01")
    DTAC_01("DTAC01"),
    @XmlEnumValue("DTAC02")
    DTAC_02("DTAC02"),
    @XmlEnumValue("DTAC03")
    DTAC_03("DTAC03"),
    @XmlEnumValue("DTAC04")
    DTAC_04("DTAC04"),
    @XmlEnumValue("DTAC05")
    DTAC_05("DTAC05"),
    @XmlEnumValue("DTAC06")
    DTAC_06("DTAC06"),
    @XmlEnumValue("DTAC07")
    DTAC_07("DTAC07"),
    @XmlEnumValue("DTAC08")
    DTAC_08("DTAC08"),
    @XmlEnumValue("DTID01")
    DTID_01("DTID01"),
    @XmlEnumValue("DTID02")
    DTID_02("DTID02"),
    @XmlEnumValue("DTID03")
    DTID_03("DTID03"),
    @XmlEnumValue("DTID04")
    DTID_04("DTID04"),
    @XmlEnumValue("DTID05")
    DTID_05("DTID05"),
    @XmlEnumValue("DTID06")
    DTID_06("DTID06"),
    @XmlEnumValue("DTRF01")
    DTRF_01("DTRF01"),
    @XmlEnumValue("CTAC01")
    CTAC_01("CTAC01"),
    @XmlEnumValue("TODT01")
    TODT_01("TODT01"),
    @XmlEnumValue("MNDT01")
    MNDT_01("MNDT01"),
    @XmlEnumValue("MNDT02")
    MNDT_02("MNDT02"),
    @XmlEnumValue("MNDT03")
    MNDT_03("MNDT03"),
    @XmlEnumValue("MNDT04")
    MNDT_04("MNDT04"),
    OTHERS("OTHERS");
    private final String value;

    FPSMandateAcceptanceRejectReasonCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FPSMandateAcceptanceRejectReasonCode fromValue(String v) {
        for (FPSMandateAcceptanceRejectReasonCode c: FPSMandateAcceptanceRejectReasonCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
