//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.28 at 09:26:51 上午 CST 
//


package com.forms.ffp.adaptor.jaxb.participant.request.ffpddi02;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.forms.ffp.adaptor.jaxb.participant.request.BODY;


/**
 * <p>Java class for FFPDDI02 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FFPDDI02">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SrcRefNm" type="{}RestrictedNZText_Max30"/>
 *         &lt;element name="DbtrNm" type="{}RestrictedUnicodeTextMax140"/>
 *         &lt;element name="DbtrAcTp" type="{}UpperCaseNumericText_Exact4"/>
 *         &lt;element name="DbtrAcNo" type="{}RestrictedFINZText_Max34"/>
 *         &lt;element name="SettlAmt" type="{}Restricted15Digit2AmountType"/>
 *         &lt;element name="SettlCcy" type="{}UpperCaseNumericText_Exact3"/>
 *         &lt;element name="DrctDbtTxRltId" type="{}RestrictedFINZText_Max35" minOccurs="0"/>
 *         &lt;element name="DbtrContPhone" type="{}PhoneNumber" minOccurs="0"/>
 *         &lt;element name="DbtrContEmailAddr" type="{}RestrictedFINZText_Max254" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FFPDDI02", propOrder = {
    "srcRefNm",
    "dbtrNm",
    "dbtrAcTp",
    "dbtrAcNo",
    "settlAmt",
    "settlCcy",
    "drctDbtTxRltId",
    "dbtrContPhone",
    "dbtrContEmailAddr"
})
public class FFPDDI02 extends BODY{

    @XmlElement(name = "SrcRefNm", required = true)
    protected String srcRefNm;
    @XmlElement(name = "DbtrNm", required = true)
    protected String dbtrNm;
    @XmlElement(name = "DbtrAcTp", required = true)
    protected String dbtrAcTp;
    @XmlElement(name = "DbtrAcNo", required = true)
    protected String dbtrAcNo;
    @XmlElement(name = "SettlAmt", required = true)
    protected BigDecimal settlAmt;
    @XmlElement(name = "SettlCcy", required = true)
    protected String settlCcy;
    @XmlElement(name = "DrctDbtTxRltId")
    protected String drctDbtTxRltId;
    @XmlElement(name = "DbtrContPhone")
    protected String dbtrContPhone;
    @XmlElement(name = "DbtrContEmailAddr")
    protected String dbtrContEmailAddr;

    /**
     * Gets the value of the srcRefNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcRefNm() {
        return srcRefNm;
    }

    /**
     * Sets the value of the srcRefNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcRefNm(String value) {
        this.srcRefNm = value;
    }

    /**
     * Gets the value of the dbtrNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrNm() {
        return dbtrNm;
    }

    /**
     * Sets the value of the dbtrNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrNm(String value) {
        this.dbtrNm = value;
    }

    /**
     * Gets the value of the dbtrAcTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrAcTp() {
        return dbtrAcTp;
    }

    /**
     * Sets the value of the dbtrAcTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrAcTp(String value) {
        this.dbtrAcTp = value;
    }

    /**
     * Gets the value of the dbtrAcNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrAcNo() {
        return dbtrAcNo;
    }

    /**
     * Sets the value of the dbtrAcNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrAcNo(String value) {
        this.dbtrAcNo = value;
    }

    /**
     * Gets the value of the settlAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSettlAmt() {
        return settlAmt;
    }

    /**
     * Sets the value of the settlAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSettlAmt(BigDecimal value) {
        this.settlAmt = value;
    }

    /**
     * Gets the value of the settlCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlCcy() {
        return settlCcy;
    }

    /**
     * Sets the value of the settlCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlCcy(String value) {
        this.settlCcy = value;
    }

    /**
     * Gets the value of the drctDbtTxRltId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrctDbtTxRltId() {
        return drctDbtTxRltId;
    }

    /**
     * Sets the value of the drctDbtTxRltId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrctDbtTxRltId(String value) {
        this.drctDbtTxRltId = value;
    }

    /**
     * Gets the value of the dbtrContPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrContPhone() {
        return dbtrContPhone;
    }

    /**
     * Sets the value of the dbtrContPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrContPhone(String value) {
        this.dbtrContPhone = value;
    }

    /**
     * Gets the value of the dbtrContEmailAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrContEmailAddr() {
        return dbtrContEmailAddr;
    }

    /**
     * Sets the value of the dbtrContEmailAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrContEmailAddr(String value) {
        this.dbtrContEmailAddr = value;
    }

}
