//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:51:13 ÉÏÎç CST 
//


package com.forms.ffp.adaptor.jaxb.iclfps.fps_envelope_01;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import com.forms.ffp.adaptor.jaxb.iclfps.head_001_001_01.BusinessApplicationHeaderV01;


/**
 * <p>Java class for ISO20022BusinessDataV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ISO20022BusinessDataV01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:head.001.001.01}AppHdr"/>
 *         &lt;choice>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:admi.002.001.01}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:admi.004.001.02}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:camt.052.001.06}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:camt.054.001.06}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:camt.056.001.06}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:camt.060.001.03}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.admi.001.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.admi.002.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.admi.003.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.adrs.001.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.adrs.002.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.adrs.003.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.adrs.004.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.adrs.005.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.adrs.006.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.adrs.007.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.adrs.008.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.adrs.009.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.cel.001.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.cep.001.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.cex.001.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.cex.002.001.01}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:pain.009.001.05}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.05}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:pain.011.001.05}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:pain.012.001.05}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:pain.018.001.01}Document"/>
 *           &lt;element ref="{urn:hkicl:fps:xsd:fps.edda.001.001.01}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.08}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:pacs.003.001.07}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:pacs.004.001.07}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}Document"/>
 *           &lt;element ref="{urn:iso:std:iso:20022:tech:xsd:pacs.028.001.01}Document"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ISO20022BusinessDataV01", propOrder = {
    "content"
})
public class ISO20022BusinessDataV01 {

    @XmlElementRefs({
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.cep.001.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.cex.002.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.08", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.adrs.008.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:camt.060.001.03", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:pain.018.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.adrs.001.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:admi.002.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.028.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.adrs.005.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.cel.001.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.adrs.002.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:camt.054.001.06", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.adrs.006.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.admi.002.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:camt.056.001.06", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.004.001.07", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.edda.001.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:pain.009.001.05", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.admi.003.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:pain.010.001.05", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:camt.052.001.06", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.003.001.07", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.admi.001.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:pain.012.001.05", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:admi.004.001.02", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.adrs.004.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.adrs.009.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.adrs.003.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:iso:std:iso:20022:tech:xsd:pain.011.001.05", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.adrs.007.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "Document", namespace = "urn:hkicl:fps:xsd:fps.cex.001.001.01", type = JAXBElement.class),
        @XmlElementRef(name = "AppHdr", namespace = "urn:iso:std:iso:20022:tech:xsd:head.001.001.01", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Document" is used by two different parts of a schema. See: 
     * line 104 of file:/C:/Users/qingzhizi/working/Project/FFP/Workspaces/FFPWorkspace2/ffp_jaxb/schema/iclfps/fps.envelope.01.xsd
     * line 103 of file:/C:/Users/qingzhizi/working/Project/FFP/Workspaces/FFPWorkspace2/ffp_jaxb/schema/iclfps/fps.envelope.01.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_cep_001_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_cex_002_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.pacs_002_001_08.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_adrs_008_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.camt_060_001_03.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.pain_018_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_adrs_001_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.admi_002_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.pacs_028_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_adrs_005_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_cel_001_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_adrs_002_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.camt_054_001_06.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_adrs_006_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_admi_002_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.pacs_008_001_06.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.camt_056_001_06.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.pacs_004_001_07.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_edda_001_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.pain_009_001_05.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_admi_003_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.pain_010_001_05.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.camt_052_001_06.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.pacs_003_001_07.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_admi_001_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.pain_012_001_05.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.admi_004_001_02.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_adrs_004_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_adrs_009_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_adrs_003_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.pain_011_001_05.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_adrs_007_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link com.forms.ffp.adaptor.jaxb.iclfps.fps_cex_001_001_01.Document }{@code >}
     * {@link JAXBElement }{@code <}{@link BusinessApplicationHeaderV01 }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

}
